allowBuilds:
  '0': '@firebase/util'
  '1': '@parcel/watcher'
  '2': core-js
  '3': esbuild
  '4': protobufjs
  '@firebase/util': set this to true or false
  '@parcel/watcher': set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@4.0.24'
  - '@ai-sdk/google@4.0.19'
  - '@ai-sdk/react@4.0.35'
  - '@typescript-eslint/eslint-plugin@8.65.0'
  - '@typescript-eslint/parser@8.65.0'
  - '@typescript-eslint/project-service@8.65.0'
  - '@typescript-eslint/scope-manager@8.65.0'
  - '@typescript-eslint/tsconfig-utils@8.65.0'
  - '@typescript-eslint/type-utils@8.65.0'
  - '@typescript-eslint/types@8.65.0'
  - '@typescript-eslint/typescript-estree@8.65.0'
  - '@typescript-eslint/utils@8.65.0'
  - '@typescript-eslint/visitor-keys@8.65.0'
  - ai@7.0.32
  - recharts@3.10.0
  - sass@1.101.3
# https://pnpm.io/settings
overrides:
  'react': '^19.0.0'
  'react-dom': '^19.0.0'
  '@types/react': '^19.0.0'
  '@types/react-dom': '^19.0.0'
  '@babel/runtime': '^7.26.10'
  '@tootallnate/once': '^3.0.1'
  'minimatch': '^10.2.3'
  'smol-toml': '^1.6.1'
  'srvx': '^0.11.13'
  '@mui/system': '6.5.0'
