export {LogosServicios}

import DomainDisabledIcon from '@mui/icons-material/DomainDisabled'
import GraphicEqIcon from '@mui/icons-material/GraphicEq'
import HouseSidingIcon from '@mui/icons-material/HouseSiding'
import HardwareIcon from '@mui/icons-material/Hardware'
import ArchitectureIcon from '@mui/icons-material/Architecture'
import HandshakeIcon from '@mui/icons-material/Handshake'
import ConstructionIcon from '@mui/icons-material/Construction'
import PrecisionManufacturingIcon from '@mui/icons-material/PrecisionManufacturing'
import CarpenterIcon from '@mui/icons-material/Carpenter'
import SquareFootIcon from '@mui/icons-material/SquareFoot'
import VpnKeyIcon from '@mui/icons-material/VpnKey'
import BusinessIcon from '@mui/icons-material/Business'
import FingerprintIcon from '@mui/icons-material/Fingerprint'
import PestControlRodentIcon from '@mui/icons-material/PestControlRodent'
import DrawIcon from '@mui/icons-material/Draw'
import SensorsIcon from '@mui/icons-material/Sensors'
import FloodIcon from '@mui/icons-material/Flood'
import ElectricMeterIcon from '@mui/icons-material/ElectricMeter'
import FoundationIcon from '@mui/icons-material/Foundation'
import HubIcon from '@mui/icons-material/Hub'
import GasMeterIcon from '@mui/icons-material/GasMeter'
import WaterDamageIcon from '@mui/icons-material/WaterDamage'
import SupervisedUserCircleIcon from '@mui/icons-material/SupervisedUserCircle'
import ElectricBoltIcon from '@mui/icons-material/ElectricBolt'
import DesignServicesIcon from '@mui/icons-material/DesignServices'
import RoofingIcon from '@mui/icons-material/Roofing'
import ForestIcon from '@mui/icons-material/Forest'
import SensorWindowIcon from '@mui/icons-material/SensorWindow'
import LocalFloristIcon from '@mui/icons-material/LocalFlorist'
import LocalLaundryServiceIcon from '@mui/icons-material/LocalLaundryService'
import CleaningServicesIcon from '@mui/icons-material/CleaningServices'
import EngineeringIcon from '@mui/icons-material/Engineering'
import BuildIcon from '@mui/icons-material/Build'
import MoveUpIcon from '@mui/icons-material/MoveUp'
import EmojiTransportationIcon from '@mui/icons-material/EmojiTransportation'
import LandscapeIcon from '@mui/icons-material/Landscape'
import FormatPaintIcon from '@mui/icons-material/FormatPaint'
import PlumbingIcon from '@mui/icons-material/Plumbing'
import LanIcon from '@mui/icons-material/Lan'
import KitchenIcon from '@mui/icons-material/Kitchen'
import BathroomIcon from '@mui/icons-material/Bathroom'
import PoolIcon from '@mui/icons-material/Pool'
import HomeRepairServiceIcon from '@mui/icons-material/HomeRepairService'
import DryCleaningIcon from '@mui/icons-material/DryCleaning'
import CameraOutdoorIcon from '@mui/icons-material/CameraOutdoor'
import BathtubIcon from '@mui/icons-material/Bathtub'
import ChairIcon from '@mui/icons-material/Chair'
import HandymanIcon from '@mui/icons-material/Handyman'
import ThermostatAutoIcon from '@mui/icons-material/ThermostatAuto';
import DeviceThermostatIcon from '@mui/icons-material/DeviceThermostat';
import TungstenIcon from '@mui/icons-material/Tungsten';
import BlenderIcon from '@mui/icons-material/Blender';
import DeckIcon from '@mui/icons-material/Deck';
import DeliveryDiningIcon from '@mui/icons-material/DeliveryDining';
import PowerIcon from '@mui/icons-material/Power';
import ElectricalServicesIcon from '@mui/icons-material/ElectricalServices';
import WaterIcon from '@mui/icons-material/Water';
import CheckroomIcon from '@mui/icons-material/Checkroom';
import ControlCameraIcon from '@mui/icons-material/ControlCamera';
import CottageIcon from '@mui/icons-material/Cottage';
import DeskIcon from '@mui/icons-material/Desk';
import BorderBottomIcon from '@mui/icons-material/BorderBottom';


import AdminPanelSettingsIcon from '@mui/icons-material/AdminPanelSettings';
import DoneAllIcon from '@mui/icons-material/DoneAll';
import BedroomParentIcon from '@mui/icons-material/BedroomParent';
import ChaletIcon from '@mui/icons-material/Chalet';
import CameraIndoorIcon from '@mui/icons-material/CameraIndoor';
import PetsIcon from '@mui/icons-material/Pets';
import SportsMotorsportsIcon from '@mui/icons-material/SportsMotorsports';
import Diversity2Icon from '@mui/icons-material/Diversity2';
import AssistWalkerIcon from '@mui/icons-material/AssistWalker';
import WheelchairPickupIcon from '@mui/icons-material/WheelchairPickup';
import SettingsAccessibilityIcon from '@mui/icons-material/SettingsAccessibility';
import PestControlIcon from '@mui/icons-material/PestControl';
import RollerShadesIcon from '@mui/icons-material/RollerShades';
import ReduceCapacityIcon from '@mui/icons-material/ReduceCapacity';
import LightIcon from '@mui/icons-material/Light';
import GrassIcon from '@mui/icons-material/Grass';
import LocalPrintshopIcon from '@mui/icons-material/LocalPrintshop';
import ElectricCarIcon from '@mui/icons-material/ElectricCar';
import SensorOccupiedIcon from '@mui/icons-material/SensorOccupied';
import SolarPowerIcon from '@mui/icons-material/SolarPower';
import SoupKitchenIcon from '@mui/icons-material/SoupKitchen';
import ShieldMoonIcon from '@mui/icons-material/ShieldMoon';
import CoffeeMakerIcon from '@mui/icons-material/CoffeeMaker';
import WarehouseIcon from '@mui/icons-material/Warehouse';
import Groups2Icon from '@mui/icons-material/Groups2';
import RecyclingIcon from '@mui/icons-material/Recycling';
import ParkIcon from '@mui/icons-material/Park';
import TrackChangesIcon from '@mui/icons-material/TrackChanges';
import ImagesearchRollerIcon from '@mui/icons-material/ImagesearchRoller';
import SecurityIcon from '@mui/icons-material/Security';

const LogosServicios = ( ) => {

    return (
        <div className="d-flex w-50 flex-wrap mx-auto pb-5">
            <DomainDisabledIcon fontSize="large" className='p-1' /> 
            <GraphicEqIcon fontSize="large" className='p-1' />
            <HouseSidingIcon fontSize="large" className='p-1' />
            <HardwareIcon fontSize="large" className='p-1' />
            <ArchitectureIcon fontSize="large" className='p-1' />
            <HandshakeIcon fontSize="large" className='p-1' />
            <ConstructionIcon fontSize="large" className='p-1' />
            <PrecisionManufacturingIcon fontSize="large" className='p-1' />
            <CarpenterIcon fontSize="large" className='p-1' />
            <SquareFootIcon fontSize="large" className='p-1' />
            <VpnKeyIcon fontSize="large" className='p-1' />
            <BusinessIcon fontSize="large" className='p-1' />
            <FingerprintIcon fontSize="large" className='p-1' />
            <PestControlRodentIcon fontSize="large" className='p-1' />
            <DrawIcon fontSize="large" className='p-1' />
            <SensorsIcon fontSize="large" className='p-1' />
            <FloodIcon fontSize="large" className='p-1' />
            <ElectricMeterIcon fontSize="large" className='p-1' />
            <FoundationIcon fontSize="large" className='p-1' />
            <HubIcon fontSize="large" className='p-1' />
            <GasMeterIcon fontSize="large" className='p-1' />
            <WaterDamageIcon fontSize="large" className='p-1' />
            <SupervisedUserCircleIcon fontSize="large" className='p-1' />
            <ElectricBoltIcon fontSize="large" className='p-1' />
            <DesignServicesIcon fontSize="large" className='p-1' />
            <RoofingIcon fontSize="large" className='p-1' />
            <ForestIcon fontSize="large" className='p-1' />
            <SensorWindowIcon fontSize="large" className='p-1' />
            <LocalFloristIcon fontSize="large" className='p-1' />
            <LocalLaundryServiceIcon fontSize="large" className='p-1' />
            <CleaningServicesIcon fontSize="large" className='p-1' />
            <EngineeringIcon fontSize="large" className='p-1' />
            <BuildIcon fontSize="large" className='p-1' />
            <MoveUpIcon fontSize="large" className='p-1' />
            <EmojiTransportationIcon fontSize="large" className="p-1" />,
            <LanIcon fontSize="large" className='p-1' />
            <LandscapeIcon fontSize="large" className='p-1' />
            <FormatPaintIcon fontSize="large" className='p-1' />
            <PlumbingIcon fontSize="large" className='p-1' />
            <KitchenIcon fontSize="large" className='p-1' />
            <BathroomIcon fontSize="large" className='p-1' />
            <PoolIcon fontSize="large" className='p-1' />
            <HomeRepairServiceIcon fontSize="large" className='p-1' />
            <DryCleaningIcon fontSize="large" className='p-1' />
            <CameraOutdoorIcon fontSize="large" className='p-1' />
            <ChairIcon fontSize="large" className="p-1" />
            <BathtubIcon fontSize="large" className='p-1' />
            <HandymanIcon fontSize="large" className='p-1' />
            <ThermostatAutoIcon fontSize="large" className='p-1' />
            <DeviceThermostatIcon fontSize="large" className='p-1' />            
            <TungstenIcon fontSize="large" className='p-1' />
            <BlenderIcon fontSize="large" className='p-1' />
            <DeckIcon fontSize="large" className='p-1' />
            <DeliveryDiningIcon fontSize="large" className='p-1' />
            <PowerIcon fontSize="large" className='p-1' />
            <ElectricalServicesIcon fontSize="large" className='p-1' />
            <WaterIcon fontSize="large" className='p-1' />
            <CheckroomIcon fontSize="large" className='p-1' />
            <ControlCameraIcon fontSize="large" className='p-1' />  
            <CottageIcon fontSize="large" className='p-1' />  
            <DeskIcon fontSize="large" className='p-1' />  
            <BorderBottomIcon fontSize="large" className='p-1' />  
            
            <br /><br />
            <AdminPanelSettingsIcon fontSize="large" className='p-1'/>
            <DoneAllIcon fontSize="large" className='p-1' />
            <PestControlIcon fontSize="large" className='p-1' />
            <LocalPrintshopIcon fontSize="large" className='p-1' />
            <BedroomParentIcon fontSize="large" className='p-1' />
            <ChaletIcon fontSize="large" className='p-1' />
            <CameraIndoorIcon fontSize="large" className='p-1' />
            <PetsIcon fontSize="large" className='p-1' />
            <SportsMotorsportsIcon fontSize="large" className='p-1' />
            <Diversity2Icon fontSize="large" className='p-1' />
            <AssistWalkerIcon fontSize="large" className='p-1' />
            <WheelchairPickupIcon fontSize="large" className='p-1' />
            <SettingsAccessibilityIcon fontSize="large" className='p-1' />
            <RollerShadesIcon fontSize="large" className='p-1' />
            <ReduceCapacityIcon fontSize="large" className='p-1' />
            <LightIcon fontSize="large" className='p-1' />
            <GrassIcon fontSize="large" className='p-1' />
            <ElectricCarIcon fontSize="large" className='p-1' />
            <SensorOccupiedIcon fontSize="large" className='p-1' />
            <SolarPowerIcon fontSize="large" className='p-1' />
            <SoupKitchenIcon fontSize="large" className='p-1' />
            <ShieldMoonIcon fontSize="large" className='p-1' />
            <CoffeeMakerIcon fontSize="large" className='p-1' />
            <WarehouseIcon fontSize="large" className='p-1' />
            <Groups2Icon fontSize="large" className='p-1' />
            <RecyclingIcon fontSize="large" className='p-1' />
            <ParkIcon fontSize="large" className='p-1' />
            <TrackChangesIcon fontSize="large" className='p-1' />
            <ImagesearchRollerIcon fontSize="large" className='p-1' />
            <SecurityIcon fontSize="large" className='p-1' />
        </div>
    )
}