const ListadoCategorias = [
    { key: 0, label: 'Administraciones PH', variant: 'outlined' },
    { key: 1, label: 'Aislamiento acústico', variant: 'outlined' },
    { key: 2, label: 'Acabados en muros', variant: 'outlined' },
    { key: 3, label: 'Albañilería', variant: 'outlined' },
    { key: 4, label: 'Arquitectura', variant: 'outlined' },
    { key: 5, label: 'Artesanías y manualidades ', variant: 'outlined' },
    { key: 6, label: 'Asistencia toderos', variant: 'outlined' },
    { key: 7, label: 'Automatización', variant: 'outlined' },
    { key: 8, label: 'Carpintería', variant: 'outlined' },
    { key: 9, label: 'Carpintería en aluminio', variant: 'outlined' },
    { key: 10, label: 'Carpintería metálica', variant: 'outlined' },
    { key: 11, label: 'Cerrajería', variant: 'outlined' },
    { key: 12, label: 'Construcción obra', variant: 'outlined' },
    { key: 13, label: 'Control de acceso', variant: 'outlined' },
    { key: 14, label: 'Control de plagas', variant: 'outlined' },
    { key: 15, label: 'Diseño e impresión', variant: 'outlined' },
    { key: 16, label: 'Domótica', variant: 'outlined' },
    { key: 17, label: 'Electricidad', variant: 'outlined' },
    { key: 18, label: 'Estudios de suelos', variant: 'outlined' },
    { key: 19, label: 'Ferreterías', variant: 'outlined' },
    { key: 20, label: 'Gasodomésticos y refrigeración', variant: 'outlined' },
    { key: 21, label: 'Impermeabilización', variant: 'outlined' },
    { key: 22, label: 'Instalación de adoquín', variant: 'outlined' },
    {
        key: 23,
        label: 'Instalación de cableado estructurado',
        variant: 'outlined',
    },
    { key: 24, label: 'Instalación de cerámica', variant: 'outlined' },
    { key: 25, label: 'Instalación de cubiertas', variant: 'outlined' },
    { key: 26, label: 'Instalación de parques', variant: 'outlined' },
    { key: 27, label: 'Instalación de ventanas', variant: 'outlined' },
    { key: 28, label: 'Jardinería', variant: 'outlined' },
    { key: 29, label: 'Lavandería', variant: 'outlined' },
    { key: 30, label: 'Limpiezas técnicas', variant: 'outlined' },
    { key: 31, label: 'Maestro Obra', variant: 'outlined' },
    { key: 32, label: 'Mecanica', variant: 'outlined' },
    { key: 33, label: 'Movilizar pesos', variant: 'outlined' },
    { key: 34, label: 'Mudanzas', variant: 'outlined' },
    { key: 35, label: 'Paisajismo', variant: 'outlined' },
    { key: 36, label: 'Pintura', variant: 'outlined' },
    { key: 37, label: 'Plomería', variant: 'outlined' },
    { key: 38, label: 'Redes cableado estructurado', variant: 'outlined' },
    { key: 39, label: 'Reformas Cocinas', variant: 'outlined' },
    { key: 40, label: 'Reformas Baños', variant: 'outlined' },
    { key: 41, label: 'Reformas Piscinas', variant: 'outlined' },
    { key: 42, label: 'Servicio doméstico', variant: 'outlined' },
    { key: 43, label: 'Sistemas de Seguridad y alarmas', variant: 'outlined' },
    { key: 44, label: 'Tanques de agua', variant: 'outlined' },
    { key: 45, label: 'Tapicería', variant: 'outlined' },
    { key: 46, label: 'Trabajos en piedra', variant: 'outlined' },
]

export default ListadoCategorias
