const ListadoCategorias = [
    {
        key: 0,
        label: 'Administraciones PH',
        rol: 'Administradores PH',
        variant: 'outlined',
    },
    {
        key: 1,
        label: 'Aislamiento acústico',
        rol: 'Aisladores acústicos',
        variant: 'outlined',
    },
    {
        key: 2,
        label: 'Acabados en muros',
        rol: 'Afinadores de muros y acabados',
        variant: 'outlined',
    },
    { key: 3, label: 'Albañilería', rol: 'Albañiles', variant: 'outlined' },
    {
        key: 4,
        label: 'Arquitectura',
        rol: 'Arquitectos',
        variant: 'outlined',
    },
    {
        key: 5,
        label: 'Artesanías y manualidades ',
        rol: 'Artesanos',
        variant: 'outlined',
    },
    {
        key: 6,
        label: 'Asistencia toderos',
        rol: 'Toderos',
        variant: 'outlined',
    },
    {
        key: 7,
        label: 'Automatización',
        rol: 'Técnico en automatización',
        variant: 'outlined',
    },
    { key: 8, label: 'Carpintería', rol: 'Carpinteros', variant: 'outlined' },
    {
        key: 9,
        label: 'Carpintería en aluminio',
        rol: 'Carpinteros del aluminio',
        variant: 'outlined',
    },
    {
        key: 10,
        label: 'Carpintería metálica',
        rol: 'Carpinteros de metales',
        variant: 'outlined',
    },
    { key: 11, label: 'Cerrajería', rol: 'Cerrajeros', variant: 'outlined' },
    {
        key: 12,
        label: 'Construcción obra',
        rol: 'Constructoras',
        variant: 'outlined',
    },
    {
        key: 13,
        label: 'Control de acceso',
        rol: 'Integradores Control de acceso',
        variant: 'outlined',
    },
    {
        key: 14,
        label: 'Control de plagas',
        rol: 'Controladores de plagas',
        variant: 'outlined',
    },
    {
        key: 15,
        label: 'Diseño e impresión',
        rol: 'Centros de diseño grafico',
        variant: 'outlined',
    },
    {
        key: 16,
        label: 'Domótica',
        rol: 'Técnico en domótica',
        variant: 'outlined',
    },
    {
        key: 17,
        label: 'Drenajes e inundaciones',
        rol: 'Técnico en drenajes e inundaciones',
        variant: 'outlined',
    },
    {
        key: 18,
        label: 'Electricidad',
        rol: 'Electricistas',
        variant: 'outlined',
    },
    {
        key: 19,
        label: 'Estudios de suelos',
        rol: 'Geólogos',
        variant: 'outlined',
    },
    { key: 20, label: 'Ferreterías', rol: 'Ferreteros', variant: 'outlined' },
    {
        key: 21,
        label: 'Gasodomésticos',
        rol: 'Técnico en gasodomésticos',
        variant: 'outlined',
    },
    {
        key: 22,
        label: 'Impermeabilización',
        rol: 'Impermeabilizadores',
        variant: 'outlined',
    },
    {
        key: 23,
        label: 'Instalación de adoquín',
        rol: 'Instaladores de Adoquín',
        variant: 'outlined',
    },
    {
        key: 24,
        label: 'Instalación de cableado estructurado',
        rol: 'Instaladores de cableado estructurado',
        variant: 'outlined',
    },
    {
        key: 25,
        label: 'Instalación de cerámica',
        rol: 'Instaladores de cerámica',
        variant: 'outlined',
    },
    {
        key: 26,
        label: 'Instalación de cubiertas',
        rol: 'Instaladores de cubiertas',
        variant: 'outlined',
    },
    {
        key: 27,
        label: 'Instalación de parques',
        rol: 'Instaladores de parques',
        variant: 'outlined',
    },
    {
        key: 28,
        label: 'Instalación de ventanas',
        rol: 'Instaladores de ventanas',
        variant: 'outlined',
    },
    { key: 29, label: 'Jardinería', rol: 'Jardineros', variant: 'outlined' },
    { key: 30, label: 'Lavandería', rol: 'Lavanderías', variant: 'outlined' },
    {
        key: 31,
        label: 'Limpiezas técnicas',
        rol: 'Técnicos de Limpiezas técnicas',
        variant: 'outlined',
    },
    {
        key: 32,
        label: 'Maestro Obra',
        rol: 'Maestros de Obra',
        variant: 'outlined',
    },
    { key: 33, label: 'Mecanica', rol: 'Mecanicos', variant: 'outlined' },
    {
        key: 34,
        label: 'Movilizar pesos',
        rol: 'Ayudantes de movilizaciones',
        variant: 'outlined',
    },
    {
        key: 35,
        label: 'Mudanzas',
        rol: 'Ayudantes de mudanzas',
        variant: 'outlined',
    },
    { key: 36, label: 'Paisajismo', rol: 'Paisajistas', variant: 'outlined' },
    { key: 37, label: 'Pintura', rol: 'Pintores', variant: 'outlined' },
    { key: 38, label: 'Plomería', rol: 'Plomeros', variant: 'outlined' },
    {
        key: 39,
        label: 'Redes cableado estructurado',
        rol: 'Tecnicos de redes',
        variant: 'outlined',
    },
    {
        key: 40,
        label: 'Reformas Cocinas',
        rol: 'Instaladores Cocinas',
        variant: 'outlined',
    },
    {
        key: 41,
        label: 'Reformas Baños',
        rol: 'Instaladores Baños',
        variant: 'outlined',
    },
    {
        key: 42,
        label: 'Reformas Piscinas',
        rol: 'Reparadores de piscinas',
        variant: 'outlined',
    },
    {
        key: 43,
        label: 'Refrigeración',
        rol: 'Técnico en refrigeración',
        variant: 'outlined',
    },
    {
        key: 44,
        label: 'Servicio doméstico',
        rol: 'Asistentes de servicio domestico',
        variant: 'outlined',
    },
    {
        key: 45,
        label: 'Sistemas de Seguridad y alarmas',
        rol: 'Técnico en seguridad electrónica',
        variant: 'outlined',
    },
    {
        key: 46,
        label: 'Tanques de agua',
        rol: 'Técnicos de Tanques de agua',
        variant: 'outlined',
    },
    { key: 47, label: 'Tapicería', rol: 'Tapiceros', variant: 'outlined' },
    {
        key: 48,
        label: 'Trabajos en piedra',
        rol: 'Trabajadores de piedras',
        variant: 'outlined',
    },
]

export default ListadoCategorias
