/**
 * Dezzpo Facebook Growth Copywriting System
 * Strongly typed taxonomical catalog of high-conversion social media copys.
 *
 * Taxonomical Axes:
 * 1. Target (Objetivo): EXPOSICION | VENTAS
 * 2. Intent (Intención): INTRIGA | BENEFICIO | CONVERSION
 * 3. Format (Canal/Formato): CON_URL | SIN_URL
 */

export type CopyTarget = 'EXPOSICION' | 'VENTAS';
export type CopyIntent = 'INTRIGA' | 'BENEFICIO' | 'CONVERSION';
export type CopyFormat = 'CON_URL' | 'SIN_URL';

export type TradeSpecialty =
  | 'general'
  | 'maestro'
  | 'electricista'
  | 'plomero'
  | 'pintor'
  | 'albanil'
  | 'contratista'
  | 'remodelador';

export interface CopyItem {
  readonly id: string;
  readonly target: CopyTarget;
  readonly intent: CopyIntent;
  readonly format: CopyFormat;
  readonly copy: string;
  readonly hook: string;
  readonly ctaKeyword?: string;
  readonly tradeSpecialty: TradeSpecialty;
  readonly suggestedEmoji?: string;
  readonly tags: readonly string[];
  readonly sourceOrigin: string;
}

export interface CopyFilterOptions {
  readonly target?: CopyTarget;
  readonly intent?: CopyIntent;
  readonly format?: CopyFormat;
  readonly tradeSpecialty?: TradeSpecialty;
  readonly tag?: string;
}

export interface UtmParameters {
  readonly source?: string;
  readonly medium?: string;
  readonly campaign?: string;
  readonly content?: string;
  readonly term?: string;
}

// =============================================================================
// MASTER CATALOG: FACEBOOK CAMPAIGN COPYS (100% EXHAUSTIVE FROM ALL 3 MANUALS)
// =============================================================================

export const FACEBOOK_CAMPAIGN_COPYS: readonly CopyItem[] = [
  // ---------------------------------------------------------------------------
  // 1. EXPOSICIÓN -> INTRIGA -> SIN_URL
  // ---------------------------------------------------------------------------
  {
    id: 'EXP-INT-SIN-01',
    target: 'EXPOSICION',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Trabajas excelente pero nadie te conoce fuera de tu barrio?\nComenta "PÁGINA" y te enseño a armar tu catálogo digital gratis.',
    hook: '¿Trabajas excelente pero nadie te conoce fuera de tu barrio?',
    ctaKeyword: 'PÁGINA',
    tradeSpecialty: 'general',
    tags: ['catalogo', 'visibilidad', 'barrio', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 1 #3',
  },
  {
    id: 'EXP-INT-SIN-02',
    target: 'EXPOSICION',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Sabías que puedes tener un perfil profesional como LinkedIn pero hecho para maestros de obra?\nEscribe "LINK" y te lo muestro.',
    hook: '¿Sabías que puedes tener un perfil profesional como LinkedIn pero hecho para maestros de obra?',
    ctaKeyword: 'LINK',
    tradeSpecialty: 'maestro',
    tags: ['linkedin-maestros', 'perfil-profesional', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 1 #4',
  },
  {
    id: 'EXP-INT-SIN-03',
    target: 'EXPOSICION',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'No dependas solo del voz a voz. Muestra lo que sabes hacer.\nEscríbeme y te paso el link 🔧',
    hook: 'No dependas solo del voz a voz.',
    suggestedEmoji: '🔧',
    tradeSpecialty: 'general',
    tags: ['voz-a-voz', 'dm', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Exp Sin URL #3',
  },
  {
    id: 'EXP-INT-SIN-04',
    target: 'EXPOSICION',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Nadie te encuentra cuando buscan tu oficio? Podemos ayudarte a ser visible.\nComenta "YO" 👇',
    hook: '¿Nadie te encuentra cuando buscan tu oficio?',
    ctaKeyword: 'YO',
    suggestedEmoji: '👇',
    tradeSpecialty: 'general',
    tags: ['visibilidad', 'busquedas', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Exp Sin URL #4',
  },
  {
    id: 'EXP-INT-SIN-05',
    target: 'EXPOSICION',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'No te escondas. Muestra tu trabajo donde te puedan encontrar.\nDale 👍 y te paso el link',
    hook: 'No te escondas.',
    suggestedEmoji: '👍',
    tradeSpecialty: 'general',
    tags: ['interaccion-like', 'vitrina', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Exp Sin URL #9',
  },
  {
    id: 'EXP-INT-SIN-06',
    target: 'EXPOSICION',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Tienes fotos de tus trabajos y nadie las ve?\nComenta "YO" y te cuento cómo cambiarlo 🛠️',
    hook: '¿Tienes fotos de tus trabajos y nadie las ve?',
    ctaKeyword: 'YO',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['fotos', 'portafolio', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Exp Sin URL #10',
  },
  {
    id: 'EXP-INT-SIN-07',
    target: 'EXPOSICION',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Maestro, muestra tu trabajo.\nHaz que te encuentren. 🛠️',
    hook: 'Maestro, muestra tu trabajo.',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'maestro',
    tags: ['scroll-stopper', 'maestros', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Exp #1',
  },
  {
    id: 'EXP-INT-SIN-08',
    target: 'EXPOSICION',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Muestra lo que sabes hacer.\nHaz visible tu oficio. 👷',
    hook: 'Muestra lo que sabes hacer.',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['scroll-stopper', 'oficio', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Exp #2',
  },
  {
    id: 'EXP-INT-SIN-09',
    target: 'EXPOSICION',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Tu trabajo merece ser visto.\nMuestra lo que haces. 🔧',
    hook: 'Tu trabajo merece ser visto.',
    suggestedEmoji: '🔧',
    tradeSpecialty: 'general',
    tags: ['scroll-stopper', 'reconocimiento', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Exp #3',
  },
  {
    id: 'EXP-INT-SIN-10',
    target: 'EXPOSICION',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Haz que más personas conozcan tu trabajo. 🛠️',
    hook: 'Haz que más personas conozcan tu trabajo.',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['scroll-stopper', 'alcance', 'ultra-corto'],
    sourceOrigin: 'Manual 1 - Intriga + Exp #4',
  },
  {
    id: 'EXP-INT-SIN-11',
    target: 'EXPOSICION',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'No escondas tu talento.\nMuestra tus trabajos. 🔨',
    hook: 'No escondas tu talento.',
    suggestedEmoji: '🔨',
    tradeSpecialty: 'general',
    tags: ['scroll-stopper', 'talento', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Exp #5',
  },
  {
    id: 'EXP-INT-SIN-12',
    target: 'EXPOSICION',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Que tu trabajo hable por ti. 👷',
    hook: 'Que tu trabajo hable por ti.',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['scroll-stopper', 'calidad', 'ultra-corto'],
    sourceOrigin: 'Manual 1 - Intriga + Exp #6',
  },
  {
    id: 'EXP-INT-SIN-13',
    target: 'EXPOSICION',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Haz visible tu oficio.\nMuestra lo que haces. 🛠️',
    hook: 'Haz visible tu oficio.',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['scroll-stopper', 'visibilidad', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Exp #7',
  },
  {
    id: 'EXP-INT-SIN-14',
    target: 'EXPOSICION',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Quién conoce el trabajo que haces?\nMuéstralo. 🔧',
    hook: '¿Quién conoce el trabajo que haces?',
    suggestedEmoji: '🔧',
    tradeSpecialty: 'general',
    tags: ['scroll-stopper', 'pregunta-gancho', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Exp #8',
  },
  {
    id: 'EXP-INT-SIN-15',
    target: 'EXPOSICION',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '🔌 Electricista, muestra tus trabajos.\nHaz que te encuentren en tu ciudad.',
    hook: 'Electricista, muestra tus trabajos.',
    suggestedEmoji: '🔌',
    tradeSpecialty: 'electricista',
    tags: ['hipersegmentado', 'electricista', 'nicho'],
    sourceOrigin: 'Manual 1 - Apertura Hipersegmentada',
  },
  {
    id: 'EXP-INT-SIN-16',
    target: 'EXPOSICION',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '🚰 Plomero, haz visible tu trabajo.\nQue los clientes te encuentren fácil.',
    hook: 'Plomero, haz visible tu trabajo.',
    suggestedEmoji: '🚰',
    tradeSpecialty: 'plomero',
    tags: ['hipersegmentado', 'plomero', 'nicho'],
    sourceOrigin: 'Manual 1 - Apertura Hipersegmentada',
  },
  {
    id: 'EXP-INT-SIN-17',
    target: 'EXPOSICION',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '🎨 Pintor, muestra lo que sabes hacer.\nHaz visible tu experiencia en acabados.',
    hook: 'Pintor, muestra lo que sabes hacer.',
    suggestedEmoji: '🎨',
    tradeSpecialty: 'pintor',
    tags: ['hipersegmentado', 'pintor', 'nicho'],
    sourceOrigin: 'Manual 1 - Apertura Hipersegmentada',
  },

  // ---------------------------------------------------------------------------
  // 2. EXPOSICIÓN -> INTRIGA -> CON_URL
  // ---------------------------------------------------------------------------
  {
    id: 'EXP-INT-CON-01',
    target: 'EXPOSICION',
    intent: 'INTRIGA',
    format: 'CON_URL',
    copy: '¿Aún mandas fotos sueltas por WhatsApp a tus clientes?\nOrganízalas todas en tu propio sitio gratis en dezzpo.com 🛠️',
    hook: '¿Aún mandas fotos sueltas por WhatsApp a tus clientes?',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['whatsapp', 'sitio-propio', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 1 #1',
  },
  {
    id: 'EXP-INT-CON-02',
    target: 'EXPOSICION',
    intent: 'INTRIGA',
    format: 'CON_URL',
    copy: '¿La gente no te encuentra cuando busca tu oficio en internet?\nHazte visible hoy mismo en dezzpo.com 👷',
    hook: '¿La gente no te encuentra cuando busca tu oficio en internet?',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['busqueda-google', 'presencia-web', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 1 #2',
  },

  // ---------------------------------------------------------------------------
  // 3. EXPOSICIÓN -> BENEFICIO -> SIN_URL
  // ---------------------------------------------------------------------------
  {
    id: 'EXP-BEN-SIN-01',
    target: 'EXPOSICION',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Muestra tu trabajo como un profesional. Si eres maestro, electricista o pintor:\nComenta "FOTOS" y abre tu vitrina gratis.',
    hook: 'Muestra tu trabajo como un profesional.',
    ctaKeyword: 'FOTOS',
    tradeSpecialty: 'general',
    tags: ['vitrina-digital', 'profesionalismo', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 1 #9',
  },
  {
    id: 'EXP-BEN-SIN-02',
    target: 'EXPOSICION',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Haz que te encuentren cuando busquen tu oficio.\nResponde con un "YO" y te paso el acceso para armar tu tarjeta digital.',
    hook: 'Haz que te encuentren cuando busquen tu oficio.',
    ctaKeyword: 'YO',
    tradeSpecialty: 'general',
    tags: ['tarjeta-digital', 'posicionamiento', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 1 #10',
  },
  {
    id: 'EXP-BEN-SIN-03',
    target: 'EXPOSICION',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Deja de perder clientes por no tener catálogo.\nEscribe "VER" y te enseño a mostrar tus obras gratis.',
    hook: 'Deja de perder clientes por no tener catálogo.',
    ctaKeyword: 'VER',
    tradeSpecialty: 'general',
    tags: ['catálogo-obras', 'solucion-dolor', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 1 #11',
  },
  {
    id: 'EXP-BEN-SIN-04',
    target: 'EXPOSICION',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: '¿Haces buenas remodelaciones? Haz que tu trabajo hable por ti.\nComenta "MOSTRAR" para darte tu catálogo en línea.',
    hook: '¿Haces buenas remodelaciones? Haz que tu trabajo hable por ti.',
    ctaKeyword: 'MOSTRAR',
    tradeSpecialty: 'remodelador',
    tags: ['remodelaciones', 'catálogo-online', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 1 #12',
  },
  {
    id: 'EXP-BEN-SIN-05',
    target: 'EXPOSICION',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: '¿Quieres tu propia página, como LinkedIn pero para maestros de obra?\nComenta "YO" 👷',
    hook: '¿Quieres tu propia página, como LinkedIn pero para maestros de obra?',
    ctaKeyword: 'YO',
    suggestedEmoji: '👷',
    tradeSpecialty: 'maestro',
    tags: ['linkedin-maestros', 'pagina-web', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Exp Sin URL #2',
  },
  {
    id: 'EXP-BEN-SIN-06',
    target: 'EXPOSICION',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Tu trabajo merece que lo vean. Aparece en las búsquedas gratis.\nMándame un mensaje 🛠️',
    hook: 'Tu trabajo merece que lo vean.',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['busquedas-locales', 'gratis', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Exp Sin URL #5',
  },
  {
    id: 'EXP-BEN-SIN-07',
    target: 'EXPOSICION',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: '¿Pintor, plomero o electricista? Haz visible tu trabajo con tu propia página.\nComenta "YO" 👇',
    hook: '¿Pintor, plomero o electricista?',
    ctaKeyword: 'YO',
    suggestedEmoji: '👇',
    tradeSpecialty: 'general',
    tags: ['oficios-multiples', 'pagina-propia', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Exp Sin URL #6',
  },
  {
    id: 'EXP-BEN-SIN-08',
    target: 'EXPOSICION',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: '¿Quieres que más personas conozcan tu trabajo?\nComenta "YO" 👇 y te cuento cómo',
    hook: '¿Quieres que más personas conozcan tu trabajo?',
    ctaKeyword: 'YO',
    suggestedEmoji: '👇',
    tradeSpecialty: 'general',
    tags: ['alcance-organico', 'comentarios', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Exp Sin URL #8',
  },
  {
    id: 'EXP-BEN-SIN-09',
    target: 'EXPOSICION',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Muestra tus mejores trabajos y haz visible tu oficio. 👷',
    hook: 'Muestra tus mejores trabajos y haz visible tu oficio.',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['portafolio', 'reputacion', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Exp #1',
  },
  {
    id: 'EXP-BEN-SIN-10',
    target: 'EXPOSICION',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Ten un espacio para mostrar tus trabajos y tus servicios. 🛠️',
    hook: 'Ten un espacio para mostrar tus trabajos y tus servicios.',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['espacio-digital', 'servicios', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Exp #2',
  },
  {
    id: 'EXP-BEN-SIN-11',
    target: 'EXPOSICION',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Muestra quién eres, qué haces y cómo contactarte. 🔧',
    hook: 'Muestra quién eres, qué haces y cómo contactarte.',
    suggestedEmoji: '🔧',
    tradeSpecialty: 'general',
    tags: ['identidad-profesional', 'contacto', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Exp #3',
  },
  {
    id: 'EXP-BEN-SIN-12',
    target: 'EXPOSICION',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Tu trabajo, tus servicios y tus datos en un solo lugar. 👷',
    hook: 'Tu trabajo, tus servicios y tus datos en un solo lugar.',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['centralizacion', 'orden', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Exp #4',
  },
  {
    id: 'EXP-BEN-SIN-13',
    target: 'EXPOSICION',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Haz que más personas conozcan lo que sabes hacer. 🛠️',
    hook: 'Haz que más personas conozcan lo que sabes hacer.',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['visibilidad', 'destreza', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Exp #5',
  },
  {
    id: 'EXP-BEN-SIN-14',
    target: 'EXPOSICION',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Dale visibilidad a tu oficio y muestra tu experiencia. 🔨',
    hook: 'Dale visibilidad a tu oficio y muestra tu experiencia.',
    suggestedEmoji: '🔨',
    tradeSpecialty: 'general',
    tags: ['experiencia', 'oficio', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Exp #6',
  },
  {
    id: 'EXP-BEN-SIN-15',
    target: 'EXPOSICION',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Haz visible tu trabajo y facilita que te encuentren. 👷',
    hook: 'Haz visible tu trabajo y facilita que te encuentren.',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['facilidad', 'encontrar', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Exp #7',
  },

  // ---------------------------------------------------------------------------
  // 4. EXPOSICIÓN -> BENEFICIO -> CON_URL
  // ---------------------------------------------------------------------------
  {
    id: 'EXP-BEN-CON-01',
    target: 'EXPOSICION',
    intent: 'BENEFICIO',
    format: 'CON_URL',
    copy: 'Muestra lo que sabes hacer. Sube las fotos de tus obras gratis a dezzpo.com y ten tu propia página profesional.',
    hook: 'Muestra lo que sabes hacer.',
    tradeSpecialty: 'general',
    tags: ['fotos-obras', 'pagina-profesional', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 1 #5',
  },
  {
    id: 'EXP-BEN-CON-02',
    target: 'EXPOSICION',
    intent: 'BENEFICIO',
    format: 'CON_URL',
    copy: 'Haz visible tu servicio. Muestra tus acabados en tu propia vitrina digital gratis en dezzpo.com.',
    hook: 'Haz visible tu servicio.',
    tradeSpecialty: 'general',
    tags: ['acabados', 'vitrina-digital', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 1 #6',
  },
  {
    id: 'EXP-BEN-CON-03',
    target: 'EXPOSICION',
    intent: 'BENEFICIO',
    format: 'CON_URL',
    copy: 'Haz que más personas conozcan tu trabajo. Aparece en las búsquedas de tu zona creando tu perfil en dezzpo.com.',
    hook: 'Haz que más personas conozcan tu trabajo.',
    tradeSpecialty: 'general',
    tags: ['geolocalizacion', 'zona-local', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 1 #7',
  },
  {
    id: 'EXP-BEN-CON-04',
    target: 'EXPOSICION',
    intent: 'BENEFICIO',
    format: 'CON_URL',
    copy: 'No dependas solo del voz a voz. Ten un sitio propio con tus fotos y datos de contacto directo en dezzpo.com.',
    hook: 'No dependas solo del voz a voz.',
    tradeSpecialty: 'general',
    tags: ['independencia', 'contacto-directo', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 1 #8',
  },
  {
    id: 'EXP-BEN-CON-05',
    target: 'EXPOSICION',
    intent: 'BENEFICIO',
    format: 'CON_URL',
    copy: 'dezzpo.com es como LinkedIn, pero para maestros de obra:\nMuestra tus trabajos y aparece en búsquedas.',
    hook: 'dezzpo.com es como LinkedIn, pero para maestros de obra',
    tradeSpecialty: 'maestro',
    tags: ['linkedin-maestros', 'posicionamiento-web', 'directo'],
    sourceOrigin: 'Banco 3 - Exp Con URL #13',
  },

  // ---------------------------------------------------------------------------
  // 5. EXPOSICIÓN -> CONVERSIÓN -> SIN_URL
  // ---------------------------------------------------------------------------
  {
    id: 'EXP-CON-SIN-01',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'SIN_URL',
    copy: '¿Eres maestro de obra o contratista? Creamos una vitrina gratis para ti.\nEscribe "QUIERO" y te mando el enlace.',
    hook: '¿Eres maestro de obra o contratista?',
    ctaKeyword: 'QUIERO',
    tradeSpecialty: 'contratista',
    tags: ['contratistas', 'vitrina-gratis', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 1 #17',
  },
  {
    id: 'EXP-CON-SIN-02',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'SIN_URL',
    copy: 'Aparece en los motores de búsqueda de tu ciudad.\nComenta "PERFIL" y te mandamos el acceso instantáneo.',
    hook: 'Aparece en los motores de búsqueda de tu ciudad.',
    ctaKeyword: 'PERFIL',
    tradeSpecialty: 'general',
    tags: ['seo-local', 'acceso-inmediato', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 1 #18',
  },
  {
    id: 'EXP-CON-SIN-03',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'SIN_URL',
    copy: 'Ten tu propia página web de servicios de construcción sin pagar programadores.\nComenta "SITIO" y te la activamos.',
    hook: 'Ten tu propia página web de servicios de construcción sin pagar programadores.',
    ctaKeyword: 'SITIO',
    tradeSpecialty: 'general',
    tags: ['ahorro-dinero', 'sin-programador', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 1 #19',
  },
  {
    id: 'EXP-CON-SIN-04',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'SIN_URL',
    copy: '¿Quieres un link propio con tus mejores fotos de obra para enviarle a tus clientes?\nResponde "LISTO".',
    hook: '¿Quieres un link propio con tus mejores fotos de obra para enviarle a tus clientes?',
    ctaKeyword: 'LISTO',
    tradeSpecialty: 'general',
    tags: ['link-propio', 'enviar-clientes', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 1 #20',
  },
  {
    id: 'EXP-CON-SIN-05',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'SIN_URL',
    copy: '¿Maestro, electricista o plomero? Muestra tu trabajo.\nComenta "YO" 👇 y te paso el link 🛠️',
    hook: '¿Maestro, electricista o plomero? Muestra tu trabajo.',
    ctaKeyword: 'YO',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['oficios-multiples', 'comentario-yo', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Exp Sin URL #1',
  },
  {
    id: 'EXP-CON-SIN-06',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'SIN_URL',
    copy: 'Muestra lo que sabes hacer, no solo lo que dices.\nEscríbeme y te explico 🔨',
    hook: 'Muestra lo que sabes hacer, no solo lo que dices.',
    suggestedEmoji: '🔨',
    tradeSpecialty: 'general',
    tags: ['credibilidad', 'dm', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Exp Sin URL #7',
  },

  // ---------------------------------------------------------------------------
  // 6. EXPOSICIÓN -> CONVERSIÓN -> CON_URL
  // ---------------------------------------------------------------------------
  {
    id: 'EXP-CON-CON-01',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '🛠️ Maestro, albañil, electricista o plomero:\nSube tus fotos gratis en dezzpo.com y comparte tu enlace con tus clientes.',
    hook: 'Maestro, albañil, electricista o plomero: sube tus fotos gratis',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['sube-fotos', 'enlace-compartible', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 1 #13',
  },
  {
    id: 'EXP-CON-CON-02',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Hazte visible en tu oficio hoy.\nAbre tu catálogo de servicios sin pagar nada en dezzpo.com.',
    hook: 'Hazte visible en tu oficio hoy.',
    tradeSpecialty: 'general',
    tags: ['catalogo-gratis', 'registro-hoy', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 1 #14',
  },
  {
    id: 'EXP-CON-CON-03',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Crea tu tarjeta digital de trabajos gratis en dezzpo.com y recibe cotizaciones directo en tu WhatsApp.',
    hook: 'Crea tu tarjeta digital de trabajos gratis',
    tradeSpecialty: 'general',
    tags: ['tarjeta-digital', 'cotizaciones-whatsapp', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 1 #15',
  },
  {
    id: 'EXP-CON-CON-04',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Publica tu perfil de construcción en dezzpo.com en menos de 2 minutos.\n¡Es 100% gratis!',
    hook: 'Publica tu perfil de construcción en menos de 2 minutos',
    tradeSpecialty: 'general',
    tags: ['rapidez', 'gratis', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 1 #16',
  },
  {
    id: 'EXP-CON-CON-05',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Maestro, crea gratis tu perfil y muestra tus trabajos en dezzpo.com 🛠️',
    hook: 'Maestro, crea gratis tu perfil',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'maestro',
    tags: ['perfil-gratis', 'maestro', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Exp #1',
  },
  {
    id: 'EXP-CON-CON-06',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Haz visible tu oficio.\nCrea gratis tu perfil en dezzpo.com 👷',
    hook: 'Haz visible tu oficio.',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['visibilidad', 'perfil-gratis', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Exp #2',
  },
  {
    id: 'EXP-CON-CON-07',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Muestra lo que sabes hacer en tu propio perfil dezzpo.com 🔧',
    hook: 'Muestra lo que sabes hacer',
    suggestedEmoji: '🔧',
    tradeSpecialty: 'general',
    tags: ['perfil-propio', 'habilidades', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Exp #3',
  },
  {
    id: 'EXP-CON-CON-08',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Muestra tus trabajos y tus datos en dezzpo.com 🛠️',
    hook: 'Muestra tus trabajos y tus datos',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['datos-contacto', 'fotos', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Exp #4',
  },
  {
    id: 'EXP-CON-CON-09',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Crea tu espacio para mostrar tus trabajos en dezzpo.com 👷',
    hook: 'Crea tu espacio para mostrar tus trabajos',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['espacio-propio', 'obras', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Exp #5',
  },
  {
    id: 'EXP-CON-CON-10',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Tu trabajo merece un lugar donde mostrarlo.\ndezzpo.com 🔨',
    hook: 'Tu trabajo merece un lugar donde mostrarlo.',
    suggestedEmoji: '🔨',
    tradeSpecialty: 'general',
    tags: ['dignidad-laboral', 'vitrina', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Exp #6',
  },
  {
    id: 'EXP-CON-CON-11',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Haz que más personas conozcan tu trabajo.\nMuéstralo en dezzpo.com 🛠️',
    hook: 'Haz que más personas conozcan tu trabajo.',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['alcance', 'dezzpo', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Exp #7',
  },
  {
    id: 'EXP-CON-CON-12',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Muestra tus servicios y tu experiencia en dezzpo.com 👷',
    hook: 'Muestra tus servicios y tu experiencia',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['servicios', 'experiencia', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Exp #8',
  },
  {
    id: 'EXP-CON-CON-13',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '🛠️ Maestro, haz que te encuentren.\nMuestra tus servicios en dezzpo.com',
    hook: 'Maestro, haz que te encuentren.',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'maestro',
    tags: ['maestro', 'encuentrame', 'directo'],
    sourceOrigin: 'Banco 3 - Exp Con URL #11',
  },
  {
    id: 'EXP-CON-CON-14',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿Eres maestro, albañil, electricista, plomero o pintor?\nHazte visible en dezzpo.com 🛠️',
    hook: '¿Eres maestro, albañil, electricista, plomero o pintor?',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['oficios-varios', 'visibilidad-web', 'directo'],
    sourceOrigin: 'Banco 3 - Exp Con URL #12',
  },
  {
    id: 'EXP-CON-CON-15',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿La gente no te encuentra cuando busca tu oficio?\nCrea tu perfil gratis en dezzpo.com 🔧',
    hook: '¿La gente no te encuentra cuando busca tu oficio?',
    suggestedEmoji: '🔧',
    tradeSpecialty: 'general',
    tags: ['solucion-invisibilidad', 'perfil-gratis', 'directo'],
    sourceOrigin: 'Banco 3 - Exp Con URL #14',
  },
  {
    id: 'EXP-CON-CON-16',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'No dependas solo del voz a voz.\nCrea tu tarjeta digital gratis en dezzpo.com',
    hook: 'No dependas solo del voz a voz.',
    tradeSpecialty: 'general',
    tags: ['tarjeta-digital', 'romper-dependencia', 'directo'],
    sourceOrigin: 'Banco 3 - Exp Con URL #15',
  },
  {
    id: 'EXP-CON-CON-17',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Muestra lo que sabes hacer.\nCrea tu perfil gratis en dezzpo.com y que te encuentren 👷',
    hook: 'Muestra lo que sabes hacer.',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['crear-perfil', 'encontrar', 'directo'],
    sourceOrigin: 'Banco 3 - Exp Con URL #16',
  },
  {
    id: 'EXP-CON-CON-18',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Tu trabajo habla por ti.\nSúbelo a dezzpo.com 🛠️',
    hook: 'Tu trabajo habla por ti.',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['sube-fotos', 'calidad', 'directo'],
    sourceOrigin: 'Banco 3 - Exp Con URL #17',
  },
  {
    id: 'EXP-CON-CON-19',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿Fotos de tus trabajos guardadas y nadie las ve?\nSúbelas a dezzpo.com',
    hook: '¿Fotos de tus trabajos guardadas y nadie las ve?',
    tradeSpecialty: 'general',
    tags: ['fotos-galeria', 'vitrina-web', 'directo'],
    sourceOrigin: 'Banco 3 - Exp Con URL #18',
  },
  {
    id: 'EXP-CON-CON-20',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Crea tu página gratis en dezzpo.com — tu tarjeta de presentación, pero en internet 🔧',
    hook: 'Crea tu página gratis en dezzpo.com',
    suggestedEmoji: '🔧',
    tradeSpecialty: 'general',
    tags: ['tarjeta-presentacion', 'pagina-web', 'directo'],
    sourceOrigin: 'Banco 3 - Exp Con URL #19',
  },
  {
    id: 'EXP-CON-CON-21',
    target: 'EXPOSICION',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Haz que más personas conozcan tu trabajo.\nRegístrate gratis en dezzpo.com 👷',
    hook: 'Haz que más personas conozcan tu trabajo.',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['registro-gratis', 'alcance', 'directo'],
    sourceOrigin: 'Banco 3 - Exp Con URL #20',
  },

  // ===========================================================================
  // 7. VENTAS -> INTRIGA -> SIN_URL
  // ===========================================================================
  {
    id: 'VTA-INT-SIN-01',
    target: 'VENTAS',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Quieres que te lleguen solicitudes de cotización sin estar persiguiendo gente?\nComenta "OBRAS" y te explico cómo.',
    hook: '¿Quieres que te lleguen solicitudes de cotización sin estar persiguiendo gente?',
    ctaKeyword: 'OBRAS',
    tradeSpecialty: 'general',
    tags: ['cotizaciones', 'sin-perseguir', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 2 #3',
  },
  {
    id: 'VTA-INT-SIN-02',
    target: 'VENTAS',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Buscas más trabajos cerca de donde vives?\nEstamos conectando maestros con clientes directos. Escribe "CERCA".',
    hook: '¿Buscas más trabajos cerca de donde vives?',
    ctaKeyword: 'CERCA',
    tradeSpecialty: 'maestro',
    tags: ['trabajos-cerca', 'clientes-directos', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 2 #4',
  },
  {
    id: 'VTA-INT-SIN-03',
    target: 'VENTAS',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Deja de buscar clientes uno por uno. Que te escriban a ti.\nComenta "YO" 🔧',
    hook: 'Deja de buscar clientes uno por uno.',
    ctaKeyword: 'YO',
    suggestedEmoji: '🔧',
    tradeSpecialty: 'general',
    tags: ['automatizacion', 'inbound', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Clientes Sin URL #3',
  },
  {
    id: 'VTA-INT-SIN-04',
    target: 'VENTAS',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Cansado de que no te llamen para cotizar?\nEscríbeme y te paso el link 👷',
    hook: '¿Cansado de que no te llamen para cotizar?',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['falta-llamadas', 'dm', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Clientes Sin URL #6',
  },
  {
    id: 'VTA-INT-SIN-05',
    target: 'VENTAS',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Muestra tu trabajo.\nHaz que te encuentren y te contacten. 🛠️',
    hook: 'Muestra tu trabajo.',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['contactos', 'scroll-stopper', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Ventas #1',
  },
  {
    id: 'VTA-INT-SIN-06',
    target: 'VENTAS',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Si haces un buen trabajo, haz que más personas lo vean. 👷',
    hook: 'Si haces un buen trabajo',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['buen-trabajo', 'scroll-stopper', 'ultra-corto'],
    sourceOrigin: 'Manual 1 - Intriga + Ventas #2',
  },
  {
    id: 'VTA-INT-SIN-07',
    target: 'VENTAS',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Tu trabajo puede abrirte nuevas oportunidades.\nMuéstralo. 🔧',
    hook: 'Tu trabajo puede abrirte nuevas oportunidades.',
    suggestedEmoji: '🔧',
    tradeSpecialty: 'general',
    tags: ['oportunidades', 'scroll-stopper', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Ventas #3',
  },
  {
    id: 'VTA-INT-SIN-08',
    target: 'VENTAS',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Que tu trabajo hable por ti y te acerque a nuevos clientes. 🛠️',
    hook: 'Que tu trabajo hable por ti',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['nuevos-clientes', 'calidad', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Ventas #4',
  },
  {
    id: 'VTA-INT-SIN-09',
    target: 'VENTAS',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Más personas viendo tu trabajo.\nMás oportunidades para ti. 👷',
    hook: 'Más personas viendo tu trabajo.',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['volumen', 'oportunidades', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Ventas #5',
  },
  {
    id: 'VTA-INT-SIN-10',
    target: 'VENTAS',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Haz visible tu oficio y deja que te encuentren. 🔨',
    hook: 'Haz visible tu oficio',
    suggestedEmoji: '🔨',
    tradeSpecialty: 'general',
    tags: ['visibilidad', 'captacion', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Ventas #6',
  },
  {
    id: 'VTA-INT-SIN-11',
    target: 'VENTAS',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Muestra lo que sabes hacer.\nHazte visible para nuevas oportunidades. 🛠️',
    hook: 'Muestra lo que sabes hacer.',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['oportunidades-laborales', 'destreza', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Ventas #7',
  },

  // ---------------------------------------------------------------------------
  // 8. VENTAS -> INTRIGA -> CON_URL
  // ---------------------------------------------------------------------------
  {
    id: 'VTA-INT-CON-01',
    target: 'VENTAS',
    intent: 'INTRIGA',
    format: 'CON_URL',
    copy: '¿Cansado de buscar clientes uno por uno?\nMuestra tus trabajos en dezzpo.com y deja que te busquen a ti.',
    hook: '¿Cansado de buscar clientes uno por uno?',
    tradeSpecialty: 'general',
    tags: ['inbound', 'ahorro-tiempo', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 2 #1',
  },
  {
    id: 'VTA-INT-CON-02',
    target: 'VENTAS',
    intent: 'INTRIGA',
    format: 'CON_URL',
    copy: '¿Te quedaste sin obra esta semana?\nPublica tus fotos en dezzpo.com y conéctate con dueños de proyectos.',
    hook: '¿Te quedaste sin obra esta semana?',
    tradeSpecialty: 'general',
    tags: ['sin-obra', 'duenos-proyectos', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 2 #2',
  },

  // ---------------------------------------------------------------------------
  // 9. VENTAS -> BENEFICIO -> SIN_URL
  // ---------------------------------------------------------------------------
  {
    id: 'VTA-BEN-SIN-01',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Consigue más obras para tu bolsillo.\nComenta "DIRECTO" para mostrar tus servicios a dueños de casas sin comisiones.',
    hook: 'Consigue más obras para tu bolsillo.',
    ctaKeyword: 'DIRECTO',
    tradeSpecialty: 'general',
    tags: ['sin-comisiones', 'duenos-casas', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 2 #9',
  },
  {
    id: 'VTA-BEN-SIN-02',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: '¿Eres plomero, electricista o pintor y quieres más trabajo?\nResponde "CLIENTES" y te escribo por privado.',
    hook: '¿Eres plomero, electricista o pintor y quieres más trabajo?',
    ctaKeyword: 'CLIENTES',
    tradeSpecialty: 'general',
    tags: ['oficios-especializados', 'mas-trabajo', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 2 #10',
  },
  {
    id: 'VTA-BEN-SIN-03',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Deja de regalar tu trabajo a intermediarios.\nEscribe "COTIZAR" y te paso la herramienta para recibir llamadas directas.',
    hook: 'Deja de regalar tu trabajo a intermediarios.',
    ctaKeyword: 'COTIZAR',
    tradeSpecialty: 'general',
    tags: ['sin-intermediarios', 'llamadas-directas', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 2 #11',
  },
  {
    id: 'VTA-BEN-SIN-04',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Haz que más personas te contraten. Muestra lo que sabes hacer y recibe trabajo en tu zona.\nEscribe "AGENDA".',
    hook: 'Haz que más personas te contraten.',
    ctaKeyword: 'AGENDA',
    tradeSpecialty: 'general',
    tags: ['agenda-llena', 'zona-local', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 2 #12',
  },
  {
    id: 'VTA-BEN-SIN-05',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: '¿Quieres que te lleguen clientes sin buscarlos?\nComenta "YO" 👇 y te paso el link 👷',
    hook: '¿Quieres que te lleguen clientes sin buscarlos?',
    ctaKeyword: 'YO',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['atraccion-pasiva', 'comentario-yo', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Clientes Sin URL #1',
  },
  {
    id: 'VTA-BEN-SIN-06',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: '¿Buscas más trabajos de construcción?\nTe conectamos con clientes directos. Escribe "YO" 👇',
    hook: '¿Buscas más trabajos de construcción?',
    ctaKeyword: 'YO',
    suggestedEmoji: '👇',
    tradeSpecialty: 'general',
    tags: ['clientes-directos', 'construccion', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Clientes Sin URL #2',
  },
  {
    id: 'VTA-BEN-SIN-07',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: '¿Quieres recibir solicitudes de trabajo sin publicar en todos lados?\nMándame un mensaje 🛠️',
    hook: '¿Quieres recibir solicitudes de trabajo sin publicar en todos lados?',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['sin-spam', 'solicitudes-directas', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Clientes Sin URL #4',
  },
  {
    id: 'VTA-BEN-SIN-08',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: '¿Maestro, plomero o electricista? Recibe contactos de clientes en tu celular.\nComenta "YO" 👇',
    hook: '¿Maestro, plomero o electricista?',
    ctaKeyword: 'YO',
    suggestedEmoji: '👇',
    tradeSpecialty: 'general',
    tags: ['celular-whatsapp', 'contactos-clientes', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Clientes Sin URL #5',
  },
  {
    id: 'VTA-BEN-SIN-09',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: '¿Quieres más trabajos cerca de ti?\nComenta "YO" 👇 y te paso el link gratis',
    hook: '¿Quieres más trabajos cerca de ti?',
    ctaKeyword: 'YO',
    suggestedEmoji: '👇',
    tradeSpecialty: 'general',
    tags: ['geolocalizacion', 'link-gratis', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Clientes Sin URL #8',
  },
  {
    id: 'VTA-BEN-SIN-10',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Que los clientes te encuentren a ti primero.\nDale 👍 y te mando el link',
    hook: 'Que los clientes te encuentren a ti primero.',
    suggestedEmoji: '👍',
    tradeSpecialty: 'general',
    tags: ['primer-lugar', 'reaccion-like', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Clientes Sin URL #9',
  },
  {
    id: 'VTA-BEN-SIN-11',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: '¿Quieres cotizar trabajos sin salir a buscarlos?\nComenta "YO" y te explico 🛠️',
    hook: '¿Quieres cotizar trabajos sin salir a buscarlos?',
    ctaKeyword: 'YO',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['cotizaciones', 'ahorro-tiempo', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Clientes Sin URL #10',
  },
  {
    id: 'VTA-BEN-SIN-12',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Haz visible tu servicio y facilita que te contacten. 🛠️',
    hook: 'Haz visible tu servicio y facilita que te contacten.',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['facilidad-contacto', 'visibilidad', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Ventas #1',
  },
  {
    id: 'VTA-BEN-SIN-13',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Muestra tus trabajos y abre la puerta a nuevas oportunidades. 👷',
    hook: 'Muestra tus trabajos y abre la puerta a nuevas oportunidades.',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['oportunidades', 'puertas-abiertas', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Ventas #2',
  },
  {
    id: 'VTA-BEN-SIN-14',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Más visibilidad para tu trabajo.\nMás oportunidades para ti. 🔧',
    hook: 'Más visibilidad para tu trabajo.',
    suggestedEmoji: '🔧',
    tradeSpecialty: 'general',
    tags: ['crecimiento', 'visibilidad', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Ventas #3',
  },
  {
    id: 'VTA-BEN-SIN-15',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Muestra lo que haces y facilita que nuevos clientes te encuentren. 🛠️',
    hook: 'Muestra lo que haces',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['nuevos-clientes', 'captacion', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Ventas #4',
  },
  {
    id: 'VTA-BEN-SIN-16',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Tu trabajo puede traer nuevas oportunidades.\nHazlo visible. 👷',
    hook: 'Tu trabajo puede traer nuevas oportunidades.',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['visibilidad', 'oportunidades', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Ventas #5',
  },
  {
    id: 'VTA-BEN-SIN-17',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Muestra tus trabajos y permite que te contacten directamente. 🔨',
    hook: 'Muestra tus trabajos y permite que te contacten directamente.',
    suggestedEmoji: '🔨',
    tradeSpecialty: 'general',
    tags: ['contacto-directo', 'obras', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Ventas #6',
  },
  {
    id: 'VTA-BEN-SIN-18',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Haz visible tu oficio y conecta con personas que buscan tu trabajo. 🛠️',
    hook: 'Haz visible tu oficio',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['clientes-buscando', 'conexion', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Ventas #7',
  },

  // ---------------------------------------------------------------------------
  // 10. VENTAS -> BENEFICIO -> CON_URL
  // ---------------------------------------------------------------------------
  {
    id: 'VTA-BEN-CON-01',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'CON_URL',
    copy: 'Consigue más obras para tu bolsillo.\nMuestra tus servicios gratis en dezzpo.com y recibe solicitudes directas.',
    hook: 'Consigue más obras para tu bolsillo.',
    tradeSpecialty: 'general',
    tags: ['solicitudes-directas', 'obras', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 2 #5',
  },
  {
    id: 'VTA-BEN-CON-02',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'CON_URL',
    copy: '¿Buscas más trabajo de construcción o remodelación?\nPublique gratis en dezzpo.com y reciba contactos directos.',
    hook: '¿Buscas más trabajo de construcción o remodelación?',
    tradeSpecialty: 'remodelador',
    tags: ['remodelacion', 'contactos-directos', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 2 #6',
  },
  {
    id: 'VTA-BEN-CON-03',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'CON_URL',
    copy: 'Llena tu agenda de trabajo.\nRegistra tu oficio gratis en dezzpo.com y empieza a recibir llamadas.',
    hook: 'Llena tu agenda de trabajo.',
    tradeSpecialty: 'general',
    tags: ['agenda-llena', 'llamadas', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 2 #7',
  },
  {
    id: 'VTA-BEN-CON-04',
    target: 'VENTAS',
    intent: 'BENEFICIO',
    format: 'CON_URL',
    copy: '¿Ofreces servicios de plomería, pintura o electricidad?\nConsigue más contratos mostrando tu trabajo en dezzpo.com.',
    hook: '¿Ofreces servicios de plomería, pintura o electricidad?',
    tradeSpecialty: 'general',
    tags: ['mas-contratos', 'oficios', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 2 #8',
  },

  // ---------------------------------------------------------------------------
  // 11. VENTAS -> CONVERSIÓN -> SIN_URL
  // ---------------------------------------------------------------------------
  {
    id: 'VTA-CON-SIN-01',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'SIN_URL',
    copy: '¿Quieres recibir mensajes de personas que necesitan maestros de obra?\nComenta "YO" y te doy el acceso gratis.',
    hook: '¿Quieres recibir mensajes de personas que necesitan maestros de obra?',
    ctaKeyword: 'YO',
    tradeSpecialty: 'maestro',
    tags: ['maestros-obra', 'acceso-gratis', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 2 #17',
  },
  {
    id: 'VTA-CON-SIN-02',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'SIN_URL',
    copy: 'Haz que te llamen a contratar.\nDeja la palabra "TRABAJO" abajo y te enseño a recibir solicitudes.',
    hook: 'Haz que te llamen a contratar.',
    ctaKeyword: 'TRABAJO',
    tradeSpecialty: 'general',
    tags: ['contratacion', 'solicitudes', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 2 #18',
  },
  {
    id: 'VTA-CON-SIN-03',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'SIN_URL',
    copy: 'Estamos activando perfiles de maestros en tu zona.\nComenta "MÁS" para enviarte el link de registro inmediato.',
    hook: 'Estamos activando perfiles de maestros en tu zona.',
    ctaKeyword: 'MÁS',
    tradeSpecialty: 'maestro',
    tags: ['activacion-zona', 'registro-inmediato', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 2 #19',
  },
  {
    id: 'VTA-CON-SIN-04',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'SIN_URL',
    copy: '¿Tienes espacio en tu agenda esta semana?\nEscribe "DISPONIBLE" y te paso el link para publicar tus servicios.',
    hook: '¿Tienes espacio en tu agenda esta semana?',
    ctaKeyword: 'DISPONIBLE',
    tradeSpecialty: 'general',
    tags: ['disponibilidad-inmediata', 'publicar-servicios', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 2 #20',
  },
  {
    id: 'VTA-CON-SIN-05',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'SIN_URL',
    copy: 'Publica tu servicio y que los clientes te escriban a ti.\nComenta "YO" 🔨',
    hook: 'Publica tu servicio y que los clientes te escriban a ti.',
    ctaKeyword: 'YO',
    suggestedEmoji: '🔨',
    tradeSpecialty: 'general',
    tags: ['publicacion-servicios', 'comentario-yo', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Clientes Sin URL #7',
  },

  // ---------------------------------------------------------------------------
  // 12. VENTAS -> CONVERSIÓN -> CON_URL
  // ---------------------------------------------------------------------------
  {
    id: 'VTA-CON-CON-01',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Recibe solicitudes de trabajo directo en tu celular.\nPublica tu perfil gratis en dezzpo.com.',
    hook: 'Recibe solicitudes de trabajo directo en tu celular.',
    tradeSpecialty: 'general',
    tags: ['celular', 'perfil-gratis', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 2 #13',
  },
  {
    id: 'VTA-CON-CON-02',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Más contratos para tu negocio de construcción.\nRegistra tu cuenta hoy en dezzpo.com sin pagar comisiones.',
    hook: 'Más contratos para tu negocio de construcción.',
    tradeSpecialty: 'contratista',
    tags: ['sin-comisiones', 'negocio-construccion', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 2 #14',
  },
  {
    id: 'VTA-CON-CON-03',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'No esperes a que te recomienden.\nMuestra tus fotos en dezzpo.com y recibe cotizaciones hoy mismo.',
    hook: 'No esperes a que te recomienden.',
    tradeSpecialty: 'general',
    tags: ['cotizaciones-hoy', 'galeria-obras', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 2 #15',
  },
  {
    id: 'VTA-CON-CON-04',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Aparece cuando alguien en tu ciudad busque un maestro de obra.\nRegístrate gratis en dezzpo.com.',
    hook: 'Aparece cuando alguien en tu ciudad busque un maestro de obra.',
    tradeSpecialty: 'maestro',
    tags: ['busqueda-ciudad', 'maestro-obra', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 2 #16',
  },
  {
    id: 'VTA-CON-CON-05',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Muestra tu trabajo y haz que te encuentren.\nRegístrate gratis en dezzpo.com 🛠️',
    hook: 'Muestra tu trabajo y haz que te encuentren.',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['registro-gratis', 'encuentrame', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Ventas #1',
  },
  {
    id: 'VTA-CON-CON-06',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Haz visible tu servicio y recibe contactos en dezzpo.com 👷',
    hook: 'Haz visible tu servicio',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['recibe-contactos', 'servicio', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Ventas #2',
  },
  {
    id: 'VTA-CON-CON-07',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Muestra lo que sabes hacer y encuentra nuevas oportunidades en dezzpo.com 🔧',
    hook: 'Muestra lo que sabes hacer',
    suggestedEmoji: '🔧',
    tradeSpecialty: 'general',
    tags: ['nuevas-oportunidades', 'talento', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Ventas #3',
  },
  {
    id: 'VTA-CON-CON-08',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Muestra tus trabajos en dezzpo.com y facilita que te contacten. 👷',
    hook: 'Muestra tus trabajos en dezzpo.com',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['contacto-facil', 'obras', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Ventas #5',
  },
  {
    id: 'VTA-CON-CON-09',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Tu trabajo puede conseguirte nuevas oportunidades.\nMuéstralo en dezzpo.com 🔨',
    hook: 'Tu trabajo puede conseguirte nuevas oportunidades.',
    suggestedEmoji: '🔨',
    tradeSpecialty: 'general',
    tags: ['oportunidades', 'vitrina', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Ventas #6',
  },
  {
    id: 'VTA-CON-CON-10',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Haz visible tu oficio y deja que los clientes te encuentren en dezzpo.com 🛠️',
    hook: 'Haz visible tu oficio',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['clientes-te-encuentran', 'visibilidad', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Ventas #7',
  },
  {
    id: 'VTA-CON-CON-11',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Muestra tus trabajos, recibe solicitudes y conecta directo en dezzpo.com 👷',
    hook: 'Muestra tus trabajos',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['solicitudes', 'conexion-directa', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Ventas #8',
  },
  {
    id: 'VTA-CON-CON-12',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Maestro, muestra tu trabajo en dezzpo.com y deja que te encuentren. 🔧',
    hook: 'Maestro, muestra tu trabajo en dezzpo.com',
    suggestedEmoji: '🔧',
    tradeSpecialty: 'maestro',
    tags: ['maestro', 'captacion', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Ventas #9',
  },
  {
    id: 'VTA-CON-CON-13',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Crea tu perfil gratis en dezzpo.com y muestra lo que haces para que te encuentren. 🛠️',
    hook: 'Crea tu perfil gratis en dezzpo.com',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['crear-perfil', 'registro', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Ventas #10',
  },
  {
    id: 'VTA-CON-CON-14',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿Eres maestro de obra?\nMuestra tu trabajo y consigue clientes en dezzpo.com 🛠️',
    hook: '¿Eres maestro de obra?',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'maestro',
    tags: ['maestro-obra', 'conseguir-clientes', 'directo'],
    sourceOrigin: 'Banco 3 - Clientes Con URL #11',
  },
  {
    id: 'VTA-CON-CON-15',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿Es maestro de obra o contratista y busca más trabajo?\nRegístrese gratis en dezzpo.com',
    hook: '¿Es maestro de obra o contratista y busca más trabajo?',
    tradeSpecialty: 'contratista',
    tags: ['formal-usted', 'contratista', 'directo'],
    sourceOrigin: 'Banco 3 - Clientes Con URL #12',
  },
  {
    id: 'VTA-CON-CON-16',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Deje de buscar clientes uno por uno.\nMuestre su trabajo gratis en dezzpo.com',
    hook: 'Deje de buscar clientes uno por uno.',
    tradeSpecialty: 'general',
    tags: ['formal-usted', 'inbound', 'directo'],
    sourceOrigin: 'Banco 3 - Clientes Con URL #13',
  },
  {
    id: 'VTA-CON-CON-17',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿Ofreces servicios de construcción?\nConsigue más clientes en dezzpo.com 🛠️',
    hook: '¿Ofreces servicios de construcción?',
    suggestedEmoji: '🛠️',
    tradeSpecialty: 'general',
    tags: ['servicios-construccion', 'clientes', 'directo'],
    sourceOrigin: 'Banco 3 - Clientes Con URL #14',
  },
  {
    id: 'VTA-CON-CON-18',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿Buscas más trabajos cerca de ti?\nRegístrate gratis: dezzpo.com 🔧',
    hook: '¿Buscas más trabajos cerca de ti?',
    suggestedEmoji: '🔧',
    tradeSpecialty: 'general',
    tags: ['trabajos-cerca', 'registro-rapido', 'directo'],
    sourceOrigin: 'Banco 3 - Clientes Con URL #15',
  },
  {
    id: 'VTA-CON-CON-19',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿Eres electricista, plomero o pintor?\nRegístrate en dezzpo.com y que te encuentren 👷',
    hook: '¿Eres electricista, plomero o pintor?',
    suggestedEmoji: '👷',
    tradeSpecialty: 'general',
    tags: ['oficios', 'registro', 'directo'],
    sourceOrigin: 'Banco 3 - Clientes Con URL #16',
  },
  {
    id: 'VTA-CON-CON-20',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿Quieres cotizar más trabajos?\nMuestra tus servicios en dezzpo.com 🔧',
    hook: '¿Quieres cotizar más trabajos?',
    suggestedEmoji: '🔧',
    tradeSpecialty: 'general',
    tags: ['cotizar-mas', 'servicios', 'directo'],
    sourceOrigin: 'Banco 3 - Clientes Con URL #18',
  },
  {
    id: 'VTA-CON-CON-21',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Maestro, pintor, electricista o plomero:\nSuba sus trabajos a dezzpo.com y reciba solicitudes',
    hook: 'Maestro, pintor, electricista o plomero',
    tradeSpecialty: 'general',
    tags: ['formal-usted', 'recibir-solicitudes', 'directo'],
    sourceOrigin: 'Banco 3 - Clientes Con URL #19',
  },
  {
    id: 'VTA-CON-CON-22',
    target: 'VENTAS',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿Es maestro, plomero o electricista?\nMuestre sus trabajos en dezzpo.com y que lo coticen directo',
    hook: '¿Es maestro, plomero o electricista?',
    tradeSpecialty: 'general',
    tags: ['formal-usted', 'cotizacion-directa', 'directo'],
    sourceOrigin: 'Banco 3 - Clientes Con URL #20',
  },
] as const;

// =============================================================================
// STARTER PACK: TOP 6 PARA PRUEBAS A/B RÁPIDAS
// =============================================================================

export const STARTER_PACK_COPYS: readonly string[] = [
  'EXP-INT-SIN-07', // Maestro, muestra tu trabajo. Haz que te encuentren. 🛠️
  'EXP-INT-SIN-08', // Muestra lo que sabes hacer. Haz visible tu oficio. 👷
  'VTA-INT-SIN-05', // Muestra tu trabajo. Haz que te encuentren y te contacten. 🛠️
  'VTA-BEN-SIN-12', // Haz visible tu servicio y facilita que te contacten. 🛠️
  'EXP-CON-CON-11', // Haz que más personas conozcan tu trabajo. Muéstralo en dezzpo.com 🛠️
  'VTA-CON-CON-05', // Muestra tu trabajo y haz que te encuentren. Regístrate gratis en dezzpo.com 🛠️
] as const;

// =============================================================================
// HELPER UTILITIES
// =============================================================================

/**
 * Filter copy catalog by target, intent, format, trade specialty, or tag.
 */
export function getFilteredCopys(options: CopyFilterOptions): readonly CopyItem[] {
  return FACEBOOK_CAMPAIGN_COPYS.filter((item) => {
    if (options.target && item.target !== options.target) return false;
    if (options.intent && item.intent !== options.intent) return false;
    if (options.format && item.format !== options.format) return false;
    if (options.tradeSpecialty && item.tradeSpecialty !== options.tradeSpecialty && item.tradeSpecialty !== 'general') {
      return false;
    }
    if (options.tag && !item.tags.includes(options.tag)) return false;
    return true;
  });
}

/**
 * Retrieve a single copy by ID.
 */
export function getCopyById(id: string): CopyItem | undefined {
  return FACEBOOK_CAMPAIGN_COPYS.find((c) => c.id === id);
}

/**
 * Retrieve a random copy matching specific criteria.
 */
export function getRandomCopy(options: CopyFilterOptions): CopyItem | undefined {
  const filtered = getFilteredCopys(options);
  if (filtered.length === 0) return undefined;
  const randomIndex = Math.floor(Math.random() * filtered.length);
  return filtered[randomIndex];
}

/**
 * Builds a UTM tracking URL for social media attribution.
 */
export function buildUtmUrl(
  baseUrl = 'https://dezzpo.com',
  copyId: string,
  utmParams?: UtmParameters
): string {
  const url = new URL(baseUrl);
  url.searchParams.set('utm_source', utmParams?.source ?? 'facebook');
  url.searchParams.set('utm_medium', utmParams?.medium ?? 'group_comment');
  url.searchParams.set('utm_campaign', utmParams?.campaign ?? 'growth_maestros');
  url.searchParams.set('utm_content', utmParams?.content ?? copyId);
  if (utmParams?.term) {
    url.searchParams.set('utm_term', utmParams.term);
  }
  return url.toString();
}

/**
 * Dynamic string interpolation for hyper-segmented copy variations.
 */
export function interpolateSegmentedCopy(
  template: string,
  variables: {
    trade?: string;
    cityOrZone?: string;
    keyword?: string;
  }
): string {
  let result = template;
  if (variables.trade) {
    result = result.replace(/\{oficio\}/gi, variables.trade);
  }
  if (variables.cityOrZone) {
    result = result.replace(/\{zona\}/gi, variables.cityOrZone);
  }
  if (variables.keyword) {
    result = result.replace(/\{keyword\}/gi, variables.keyword);
  }
  return result;
}
