/**
 * Dezzpo Demand Interception Copywriting System (Homeowners & Clients)
 * Strongly typed taxonomical catalog of high-conversion Facebook copys for client acquisition.
 *
 * Taxonomical Axes:
 * 1. Segment (Ángulo de Ataque): RESPUESTA_DIRECTA | INVENTO_NECESIDAD_DM | POST_PUBLICO_SOLUCION
 * 2. Angle (Pilar de Valor): CONFIANZA | RAPIDEZ
 * 3. Intent (Intención): INTRIGA | BENEFICIO | CONVERSION
 * 4. Format (Canal/Formato): CON_URL | SIN_URL
 */

export type InterceptSegment =
  | 'RESPUESTA_DIRECTA'
  | 'INVENTO_NECESIDAD_DM'
  | 'POST_PUBLICO_SOLUCION';

export type InterceptAngle = 'CONFIANZA' | 'RAPIDEZ';
export type InterceptIntent = 'INTRIGA' | 'BENEFICIO' | 'CONVERSION';
export type InterceptFormat = 'CON_URL' | 'SIN_URL';

export type TargetTrade =
  | 'general'
  | 'plomero'
  | 'electricista'
  | 'pintor'
  | 'maestro'
  | 'remodelador'
  | 'tecnico';

export type ClientPainPoint =
  | 'DESCONFIANZA'
  | 'SPAM_MENSAJES'
  | 'INFORMALIDAD_PRECIOS'
  | 'LENTITUD_URGENCIA';

export interface ClientCopyItem {
  readonly id: string;
  readonly segment: InterceptSegment;
  readonly angle: InterceptAngle;
  readonly intent: InterceptIntent;
  readonly format: InterceptFormat;
  readonly copy: string;
  readonly hook: string;
  readonly ctaKeyword?: string;
  readonly targetTrade: TargetTrade;
  readonly painPoint: ClientPainPoint;
  readonly suggestedEmoji?: string;
  readonly tags: readonly string[];
  readonly sourceOrigin: string;
}

export interface InterceptFilterOptions {
  readonly segment?: InterceptSegment;
  readonly angle?: InterceptAngle;
  readonly intent?: InterceptIntent;
  readonly format?: InterceptFormat;
  readonly targetTrade?: TargetTrade;
  readonly painPoint?: ClientPainPoint;
  readonly tag?: string;
}

export interface ClientUtmParameters {
  readonly source?: string;
  readonly medium?: string;
  readonly campaign?: string;
  readonly content?: string;
  readonly term?: string;
}

// =============================================================================
// MASTER CATALOG: CLIENT INTERCEPT COPYS (100% EXHAUSTIVE FROM ALL 3 SOURCES)
// =============================================================================

export const CLIENT_INTERCEPT_COPYS: readonly ClientCopyItem[] = [
  // ---------------------------------------------------------------------------
  // 1. CONFIANZA -> INTRIGA -> SIN_URL
  // ---------------------------------------------------------------------------
  {
    id: 'CLI-CONF-INT-SIN-01',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Cansado de recibir 30 mensajes al privado sin saber si trabajan bien?\nComenta "VER" y te enseño a comparar sus catálogos.',
    hook: '¿Cansado de recibir 30 mensajes al privado sin saber si trabajan bien?',
    ctaKeyword: 'VER',
    targetTrade: 'general',
    painPoint: 'SPAM_MENSAJES',
    tags: ['anti-spam', 'filtro-mensajes', 'catálogo'],
    sourceOrigin: 'Manual 2 - Eje 1 #3',
  },
  {
    id: 'CLI-CONF-INT-SIN-02',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Sabías que puedes ver las fotos de obras anteriores del maestro antes de darle el anticipo?\nEscribe "FOTOS" y te lo muestro.',
    hook: '¿Sabías que puedes ver las fotos de obras anteriores del maestro antes de darle el anticipo?',
    ctaKeyword: 'FOTOS',
    targetTrade: 'maestro',
    painPoint: 'DESCONFIANZA',
    tags: ['anticipo-seguro', 'fotos-reales', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 1 #4',
  },
  {
    id: 'CLI-CONF-INT-SIN-03',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿No sabes si el plomero es bueno? Mira su trabajo antes de decidir.\nComenta "YO" 👇',
    hook: '¿No sabes si el plomero es bueno?',
    ctaKeyword: 'YO',
    suggestedEmoji: '👇',
    targetTrade: 'plomero',
    painPoint: 'DESCONFIANZA',
    tags: ['plomero', 'ver-trabajo', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Confianza Sin URL #1',
  },
  {
    id: 'CLI-CONF-INT-SIN-04',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'No contrates a ciegas. Pide ver fotos de trabajos anteriores.\nEscríbeme 🔍',
    hook: 'No contrates a ciegas.',
    suggestedEmoji: '🔍',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['no-a-ciegas', 'fotos', 'dm'],
    sourceOrigin: 'Banco 3 - Confianza Sin URL #2',
  },
  {
    id: 'CLI-CONF-INT-SIN-05',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Antes de dejar entrar a alguien a tu casa, verifica quién es.\nMándame un mensaje 🔧',
    hook: 'Antes de dejar entrar a alguien a tu casa, verifica quién es.',
    suggestedEmoji: '🔧',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['seguridad-hogar', 'verificacion', 'dm'],
    sourceOrigin: 'Banco 3 - Confianza Sin URL #3',
  },
  {
    id: 'CLI-CONF-INT-SIN-06',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'No te quedes con el primero que comenta.\nCompara antes de elegir. Comenta "YO" 👇',
    hook: 'No te quedes con el primero que comenta.',
    ctaKeyword: 'YO',
    suggestedEmoji: '👇',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['comparar', 'primero-en-comentar', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Confianza Sin URL #4',
  },
  {
    id: 'CLI-CONF-INT-SIN-07',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Y si el electricista no es tan bueno como dice? Revisa su trabajo primero.\nEscríbeme 🛠️',
    hook: '¿Y si el electricista no es tan bueno como dice?',
    suggestedEmoji: '🛠️',
    targetTrade: 'electricista',
    painPoint: 'DESCONFIANZA',
    tags: ['electricista', 'revisar-experiencia', 'dm'],
    sourceOrigin: 'Banco 3 - Confianza Sin URL #5',
  },
  {
    id: 'CLI-CONF-INT-SIN-08',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Contratar sin referencias es jugártela.\nTe cuento cómo evitarlo. Escríbeme 🔍',
    hook: 'Contratar sin referencias es jugártela.',
    suggestedEmoji: '🔍',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['referencias', 'sin-riesgos', 'dm'],
    sourceOrigin: 'Banco 3 - Confianza Sin URL #7',
  },
  {
    id: 'CLI-CONF-INT-SIN-09',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Sabes con quién vas a dejar entrar a tu hogar? Verifícalo antes.\nComenta "YO" 👇',
    hook: '¿Sabes con quién vas a dejar entrar a tu hogar?',
    ctaKeyword: 'YO',
    suggestedEmoji: '👇',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['seguridad', 'verificacion', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Confianza Sin URL #8',
  },
  {
    id: 'CLI-CONF-INT-SIN-10',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'No arriesgues tu remodelación con cualquiera.\nCompara perfiles antes. Comenta "YO" 👇',
    hook: 'No arriesgues tu remodelación con cualquiera.',
    ctaKeyword: 'YO',
    suggestedEmoji: '👇',
    targetTrade: 'remodelador',
    painPoint: 'DESCONFIANZA',
    tags: ['remodelacion', 'comparar-perfiles', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Confianza Sin URL #10',
  },
  {
    id: 'CLI-CONF-INT-SIN-11',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Buscas un profesional?\nMira primero lo que sabe hacer. 🔧',
    hook: '¿Buscas un profesional?',
    suggestedEmoji: '🔧',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['scroll-stopper', 'mira-trabajos', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Confianza #1',
  },
  {
    id: 'CLI-CONF-INT-SIN-12',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Antes de contratar, conoce los trabajos que ha realizado. 🛠️',
    hook: 'Antes de contratar',
    suggestedEmoji: '🛠️',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['trabajos-realizados', 'conocer-antes', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Confianza #2',
  },
  {
    id: 'CLI-CONF-INT-SIN-13',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Necesitas alguien para tu casa?\nEmpieza viendo su trabajo. 🏠',
    hook: '¿Necesitas alguien para tu casa?',
    suggestedEmoji: '🏠',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['arreglos-casa', 'portafolio', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Confianza #3',
  },
  {
    id: 'CLI-CONF-INT-SIN-14',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Encontrar un buen profesional puede ser más fácil. 👷',
    hook: 'Encontrar un buen profesional puede ser más fácil.',
    suggestedEmoji: '👷',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['facilidad', 'buen-profesional', 'ultra-corto'],
    sourceOrigin: 'Manual 1 - Intriga + Confianza #4',
  },
  {
    id: 'CLI-CONF-INT-SIN-15',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'No contrates a ciegas.\nMira primero sus trabajos. 🔨',
    hook: 'No contrates a ciegas.',
    suggestedEmoji: '🔨',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['no-ciegas', 'transparencia', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Confianza #5',
  },
  {
    id: 'CLI-CONF-INT-SIN-16',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Buscas plomero?\nHay una forma más fácil de encontrarlo. 🚰',
    hook: '¿Buscas plomero?',
    suggestedEmoji: '🚰',
    targetTrade: 'plomero',
    painPoint: 'DESCONFIANZA',
    tags: ['plomero', 'forma-facil', 'nicho'],
    sourceOrigin: 'Manual 1 - Intriga + Confianza #6',
  },
  {
    id: 'CLI-CONF-INT-SIN-17',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Necesitas electricista?\nConoce su trabajo antes de llamar. ⚡',
    hook: '¿Necesitas electricista?',
    suggestedEmoji: '⚡',
    targetTrade: 'electricista',
    painPoint: 'DESCONFIANZA',
    tags: ['electricista', 'conocer-antes', 'nicho'],
    sourceOrigin: 'Manual 1 - Intriga + Confianza #7',
  },
  {
    id: 'CLI-CONF-INT-SIN-18',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Buscas pintor?\nMira lo que ha hecho antes de contratarlo. 🎨',
    hook: '¿Buscas pintor?',
    suggestedEmoji: '🎨',
    targetTrade: 'pintor',
    painPoint: 'DESCONFIANZA',
    tags: ['pintor', 'acabados-reales', 'nicho'],
    sourceOrigin: 'Manual 1 - Intriga + Confianza #8',
  },

  // ---------------------------------------------------------------------------
  // 2. CONFIANZA -> INTRIGA -> CON_URL
  // ---------------------------------------------------------------------------
  {
    id: 'CLI-CONF-INT-CON-01',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'INTRIGA',
    format: 'CON_URL',
    copy: '¿Te da miedo contratar a ciegas?\nRevisa fotos reales de trabajos anteriores de especialistas en dezzpo.com 🛠️',
    hook: '¿Te da miedo contratar a ciegas?',
    suggestedEmoji: '🛠️',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['miedo-contratar', 'fotos-reales', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 1 #1',
  },
  {
    id: 'CLI-CONF-INT-CON-02',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'INTRIGA',
    format: 'CON_URL',
    copy: 'No te arriesgues con desconocidos.\nCompara perfiles y fotos de maestros de obra en dezzpo.com 👷',
    hook: 'No te arriesgues con desconocidos.',
    suggestedEmoji: '👷',
    targetTrade: 'maestro',
    painPoint: 'DESCONFIANZA',
    tags: ['sin-riesgos', 'comparar-maestros', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 1 #2',
  },

  // ---------------------------------------------------------------------------
  // 3. CONFIANZA -> BENEFICIO -> SIN_URL
  // ---------------------------------------------------------------------------
  {
    id: 'CLI-CONF-BEN-SIN-01',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Contrata con total tranquilidad.\nMira fotos de obras y opiniones de especialistas cerca de ti. Comenta "MAESTROS".',
    hook: 'Contrata con total tranquilidad.',
    ctaKeyword: 'MAESTROS',
    targetTrade: 'maestro',
    painPoint: 'DESCONFIANZA',
    tags: ['tranquilidad', 'opiniones', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 1 #9',
  },
  {
    id: 'CLI-CONF-BEN-SIN-02',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Evita sorpresas y malas remodelaciones.\nResponde con un "CATÁLOGO" y te envío el directorio con fotos de trabajos.',
    hook: 'Evita sorpresas y malas remodelaciones.',
    ctaKeyword: 'CATÁLOGO',
    targetTrade: 'remodelador',
    painPoint: 'DESCONFIANZA',
    tags: ['evitar-sorpresas', 'directorio-fotos', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 1 #10',
  },
  {
    id: 'CLI-CONF-BEN-SIN-03',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Elige al plomero o electricista viendo lo que ha hecho en otras casas.\nEscribe "VERIFICAR" y te paso el link.',
    hook: 'Elige al plomero o electricista viendo lo que ha hecho en otras casas.',
    ctaKeyword: 'VERIFICAR',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['verificado', 'otras-casas', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 1 #11',
  },
  {
    id: 'CLI-CONF-BEN-SIN-04',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Compara especialistas de construcción en un solo lugar y sin intermediarios.\nComenta "OPCIONES" para enviarte la lista.',
    hook: 'Compara especialistas de construcción en un solo lugar y sin intermediarios.',
    ctaKeyword: 'OPCIONES',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['sin-intermediarios', 'lista-opciones', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 1 #12',
  },
  {
    id: 'CLI-CONF-BEN-SIN-05',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Un comentario no dice si alguien es bueno. Sus fotos sí.\nComenta "YO" 👇',
    hook: 'Un comentario no dice si alguien es bueno. Sus fotos sí.',
    ctaKeyword: 'YO',
    suggestedEmoji: '👇',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['fotos-matan-palabras', 'evidencia', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Confianza Sin URL #6',
  },
  {
    id: 'CLI-CONF-BEN-SIN-06',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Elige viendo trabajos reales, no solo promesas.\nMándame un mensaje 🛠️',
    hook: 'Elige viendo trabajos reales, no solo promesas.',
    suggestedEmoji: '🛠️',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['trabajos-reales', 'sin-promesas', 'dm'],
    sourceOrigin: 'Banco 3 - Confianza Sin URL #9',
  },
  {
    id: 'CLI-CONF-BEN-SIN-07',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Encuentra profesionales y conoce sus trabajos antes de contactarlos. 🛠️',
    hook: 'Encuentra profesionales y conoce sus trabajos',
    suggestedEmoji: '🛠️',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['conocer-antes', 'profesionales', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Confianza #1',
  },
  {
    id: 'CLI-CONF-BEN-SIN-08',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Busca por oficio y mira lo que cada profesional sabe hacer. 🔧',
    hook: 'Busca por oficio',
    suggestedEmoji: '🔧',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['por-oficio', 'habilidades', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Confianza #2',
  },
  {
    id: 'CLI-CONF-BEN-SIN-09',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Encuentra maestros, técnicos y especialistas para tu proyecto. 🏠',
    hook: 'Encuentra maestros, técnicos y especialistas',
    suggestedEmoji: '🏠',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['especialistas', 'proyecto', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Confianza #3',
  },
  {
    id: 'CLI-CONF-BEN-SIN-10',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Conoce los servicios y trabajos de un profesional antes de llamarlo. 👷',
    hook: 'Conoce los servicios y trabajos',
    suggestedEmoji: '👷',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['antes-de-llamar', 'transparencia', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Confianza #4',
  },
  {
    id: 'CLI-CONF-BEN-SIN-11',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Más información antes de contratar.\nMejores decisiones para tu proyecto. 🔨',
    hook: 'Más información antes de contratar.',
    suggestedEmoji: '🔨',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['decisiones-inteligentes', 'informacion', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Confianza #5',
  },
  {
    id: 'CLI-CONF-BEN-SIN-12',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Busca el profesional que necesitas y revisa su experiencia. 🚰',
    hook: 'Busca el profesional que necesitas',
    suggestedEmoji: '🚰',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['experiencia-comprobada', 'revisar', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Confianza #6',
  },
  {
    id: 'CLI-CONF-BEN-SIN-13',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Encuentra servicios para tu hogar y conoce quién los realiza. ⚡',
    hook: 'Encuentra servicios para tu hogar',
    suggestedEmoji: '⚡',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['servicios-hogar', 'conocer-tecnico', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Confianza #7',
  },

  // ---------------------------------------------------------------------------
  // 4. CONFIANZA -> BENEFICIO -> CON_URL
  // ---------------------------------------------------------------------------
  {
    id: 'CLI-CONF-BEN-CON-01',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'BENEFICIO',
    format: 'CON_URL',
    copy: 'Elige bien a quién meter a tu casa.\nRevisa fotos de remodelaciones reales y contacta directo en dezzpo.com.',
    hook: 'Elige bien a quién meter a tu casa.',
    targetTrade: 'remodelador',
    painPoint: 'DESCONFIANZA',
    tags: ['seguridad', 'remodelaciones-reales', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 1 #5',
  },
  {
    id: 'CLI-CONF-BEN-CON-02',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'BENEFICIO',
    format: 'CON_URL',
    copy: 'Compara antes de contratar.\nEncuentra plomeros, electricistas y maestros con vitrina digital en dezzpo.com.',
    hook: 'Compara antes de contratar.',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['vitrina-digital', 'comparativa', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 1 #6',
  },
  {
    id: 'CLI-CONF-BEN-CON-03',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'BENEFICIO',
    format: 'CON_URL',
    copy: 'Garantiza un buen trabajo en tu hogar viendo proyectos anteriores en dezzpo.com gratis.',
    hook: 'Garantiza un buen trabajo en tu hogar',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['garantia-visual', 'proyectos-anteriores', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 1 #7',
  },
  {
    id: 'CLI-CONF-BEN-CON-04',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'BENEFICIO',
    format: 'CON_URL',
    copy: 'No pagues sin ver el trabajo del especialista.\nEncuentra perfiles con fotos de sus acabados en dezzpo.com.',
    hook: 'No pagues sin ver el trabajo del especialista.',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['fotos-acabados', 'cero-anticipos-ciegas', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 1 #8',
  },
  {
    id: 'CLI-CONF-BEN-CON-05',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'BENEFICIO',
    format: 'CON_URL',
    copy: 'dezzpo.com es como LinkedIn, pero para maestros de obra:\nVes su trabajo antes de contratar.',
    hook: 'dezzpo.com es como LinkedIn, pero para maestros de obra',
    targetTrade: 'maestro',
    painPoint: 'DESCONFIANZA',
    tags: ['linkedin-maestros', 'reputacion', 'directo'],
    sourceOrigin: 'Banco 3 - Confianza Con URL #13',
  },

  // ---------------------------------------------------------------------------
  // 5. CONFIANZA -> CONVERSIÓN -> SIN_URL
  // ---------------------------------------------------------------------------
  {
    id: 'CLI-CONF-CON-SIN-01',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'SIN_URL',
    copy: 'Te ayudamos a encontrar profesionales de construcción con fotos reales.\nEscribe "BUSCO" y te mandamos el acceso.',
    hook: 'Te ayudamos a encontrar profesionales de construcción con fotos reales.',
    ctaKeyword: 'BUSCO',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['fotos-reales', 'acceso-gratis', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 1 #17',
  },
  {
    id: 'CLI-CONF-CON-SIN-02',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'SIN_URL',
    copy: 'Encuentra maestros de obra disponibles en tu ciudad ahora mismo.\nComenta "LISTA" y te escribimos al interno.',
    hook: 'Encuentra maestros de obra disponibles en tu ciudad ahora mismo.',
    ctaKeyword: 'LISTA',
    targetTrade: 'maestro',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['maestros-disponibles', 'al-interno', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 1 #18',
  },
  {
    id: 'CLI-CONF-CON-SIN-03',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'SIN_URL',
    copy: '¿Necesitas remodelar o reparar algo? Conecta con especialistas que muestran sus trabajos.\nResponde "AYUDA".',
    hook: '¿Necesitas remodelar o reparar algo?',
    ctaKeyword: 'AYUDA',
    targetTrade: 'remodelador',
    painPoint: 'DESCONFIANZA',
    tags: ['reparar-remodelar', 'muestran-trabajos', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 1 #19',
  },
  {
    id: 'CLI-CONF-CON-SIN-04',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'SIN_URL',
    copy: 'Mira perfiles de pintores, electricistas y plomeros sin pagar comisiones.\nComenta "CONTACTO" y te paso la info.',
    hook: 'Mira perfiles de pintores, electricistas y plomeros sin pagar comisiones.',
    ctaKeyword: 'CONTACTO',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['sin-comisiones', 'perfiles', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 1 #20',
  },

  // ---------------------------------------------------------------------------
  // 6. CONFIANZA -> CONVERSIÓN -> CON_URL
  // ---------------------------------------------------------------------------
  {
    id: 'CLI-CONF-CON-CON-01',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '🛠️ Encuentra el maestro de obra o plomero ideal para tu casa en dezzpo.com y habla directo por WhatsApp.',
    hook: 'Encuentra el maestro de obra o plomero ideal para tu casa',
    suggestedEmoji: '🛠️',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['contacto-whatsapp', 'plomero-maestro', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 1 #13',
  },
  {
    id: 'CLI-CONF-CON-CON-02',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Revisa catálogos de construcción, compara profesionales y contacta gratis en dezzpo.com.',
    hook: 'Revisa catálogos de construcción',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['catalogos-gratuitos', 'comparar', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 1 #14',
  },
  {
    id: 'CLI-CONF-CON-CON-03',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Busca plomeros, electricistas o pintores disponibles cerca de tu zona hoy mismo en dezzpo.com.',
    hook: 'Busca plomeros, electricistas o pintores disponibles',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['zona-cercana', 'hoy-mismo', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 1 #15',
  },
  {
    id: 'CLI-CONF-CON-CON-04',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Consigue el especialista que necesitas viendo sus obras anteriores en dezzpo.com.\n¡Acceso 100% gratis!',
    hook: 'Consigue el especialista que necesitas',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['obras-anteriores', 'gratis', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 1 #16',
  },
  {
    id: 'CLI-CONF-CON-CON-05',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿Buscas plomero, electricista o maestro?\nEncuéntralo en dezzpo.com 🔧',
    hook: '¿Buscas plomero, electricista o maestro?',
    suggestedEmoji: '🔧',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['encuentralo', 'oficios-multiples', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Confianza #1',
  },
  {
    id: 'CLI-CONF-CON-CON-06',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Encuentra profesionales y mira sus trabajos en dezzpo.com 🛠️',
    hook: 'Encuentra profesionales y mira sus trabajos',
    suggestedEmoji: '🛠️',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['ver-trabajos', 'perfiles', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Confianza #2',
  },
  {
    id: 'CLI-CONF-CON-CON-07',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Busca el servicio que necesitas y conoce quién puede hacerlo en dezzpo.com 🏠',
    hook: 'Busca el servicio que necesitas',
    suggestedEmoji: '🏠',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['servicios', 'conoce-especialista', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Confianza #3',
  },
  {
    id: 'CLI-CONF-CON-CON-08',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Antes de contratar, revisa trabajos y servicios en dezzpo.com 👷',
    hook: 'Antes de contratar',
    suggestedEmoji: '👷',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['revisar-servicios', 'seguridad', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Confianza #4',
  },
  {
    id: 'CLI-CONF-CON-CON-09',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Encuentra maestros y profesionales para tu proyecto en dezzpo.com 🔨',
    hook: 'Encuentra maestros y profesionales',
    suggestedEmoji: '🔨',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['maestros-proyecto', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Confianza #5',
  },
  {
    id: 'CLI-CONF-CON-CON-10',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿Necesitas un profesional?\nBusca por oficio en dezzpo.com 🚰',
    hook: '¿Necesitas un profesional?',
    suggestedEmoji: '🚰',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['busca-por-oficio', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Confianza #6',
  },
  {
    id: 'CLI-CONF-CON-CON-11',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Mira trabajos, servicios y datos de contacto en dezzpo.com ⚡',
    hook: 'Mira trabajos, servicios y datos de contacto',
    suggestedEmoji: '⚡',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['datos-contacto', 'transparencia', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Confianza #7',
  },
  {
    id: 'CLI-CONF-CON-CON-12',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Encuentra profesionales para tu hogar, obra o remodelación en dezzpo.com 🎨',
    hook: 'Encuentra profesionales para tu hogar, obra o remodelación',
    suggestedEmoji: '🎨',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['remodelacion-hogar', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Confianza #8',
  },
  {
    id: 'CLI-CONF-CON-CON-13',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿No sabes si el plomero es bueno?\nMira sus trabajos reales en dezzpo.com 🔍',
    hook: '¿No sabes si el plomero es bueno?',
    suggestedEmoji: '🔍',
    targetTrade: 'plomero',
    painPoint: 'DESCONFIANZA',
    tags: ['plomero-confiable', 'trabajos-reales', 'directo'],
    sourceOrigin: 'Banco 3 - Confianza Con URL #11',
  },
  {
    id: 'CLI-CONF-CON-CON-14',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'No contrates a ciegas:\nEn dezzpo.com ves fotos de trabajos antes de decidir 🔧',
    hook: 'No contrates a ciegas',
    suggestedEmoji: '🔧',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['no-ciegas', 'fotos-trabajos', 'directo'],
    sourceOrigin: 'Banco 3 - Confianza Con URL #12',
  },
  {
    id: 'CLI-CONF-CON-CON-15',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Antes de dejarlo entrar a tu casa, revisa su perfil en dezzpo.com',
    hook: 'Antes de dejarlo entrar a tu casa',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['seguridad-casa', 'revisar-perfil', 'directo'],
    sourceOrigin: 'Banco 3 - Confianza Con URL #14',
  },
  {
    id: 'CLI-CONF-CON-CON-16',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'No te quedes con el primero que comenta.\nCompara perfiles en dezzpo.com',
    hook: 'No te quedes con el primero que comenta.',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['comparativa', 'evitar-apresurarse', 'directo'],
    sourceOrigin: 'Banco 3 - Confianza Con URL #15',
  },
  {
    id: 'CLI-CONF-CON-CON-17',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿Y si no es tan bueno como dice?\nRevisa sus trabajos en dezzpo.com 🛠️',
    hook: '¿Y si no es tan bueno como dice?',
    suggestedEmoji: '🛠️',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['duda-calidad', 'ver-evidencia', 'directo'],
    sourceOrigin: 'Banco 3 - Confianza Con URL #16',
  },
  {
    id: 'CLI-CONF-CON-CON-18',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Elige con fotos reales, no solo promesas:\ndezzpo.com',
    hook: 'Elige con fotos reales, no solo promesas',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['fotos-reales', 'sin-promesas', 'directo'],
    sourceOrigin: 'Banco 3 - Confianza Con URL #17',
  },
  {
    id: 'CLI-CONF-CON-CON-19',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Verifica antes de contratar.\nPerfiles con fotos en dezzpo.com 🔍',
    hook: 'Verifica antes de contratar.',
    suggestedEmoji: '🔍',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['verificar-perfiles', 'fotos', 'directo'],
    sourceOrigin: 'Banco 3 - Confianza Con URL #18',
  },
  {
    id: 'CLI-CONF-CON-CON-20',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Compara varios electricistas con su trabajo real en dezzpo.com',
    hook: 'Compara varios electricistas',
    targetTrade: 'electricista',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['electricistas', 'comparar-trabajos', 'directo'],
    sourceOrigin: 'Banco 3 - Confianza Con URL #19',
  },
  {
    id: 'CLI-CONF-CON-CON-21',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'CONFIANZA',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'No arriesgues tu casa con cualquiera.\nMira el trabajo antes en dezzpo.com 🛠️',
    hook: 'No arriesgues tu casa con cualquiera.',
    suggestedEmoji: '🛠️',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['cuidado-hogar', 'ver-trabajo-antes', 'directo'],
    sourceOrigin: 'Banco 3 - Confianza Con URL #20',
  },

  // ===========================================================================
  // 7. RAPIDEZ -> INTRIGA -> SIN_URL
  // ===========================================================================
  {
    id: 'CLI-RAP-INT-SIN-01',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Quieres pedir presupuestos sin llenar tu teléfono de spam?\nComenta "COTIZAR" y te explico cómo hacerlo gratis.',
    hook: '¿Quieres pedir presupuestos sin llenar tu teléfono de spam?',
    ctaKeyword: 'COTIZAR',
    targetTrade: 'general',
    painPoint: 'SPAM_MENSAJES',
    tags: ['sin-spam-telefono', 'cotizaciones', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 2 #23',
  },
  {
    id: 'CLI-RAP-INT-SIN-02',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Buscas un maestro de obra o especialista disponible hoy?\nEscribe "RÁPIDO" y te muestro dónde encontrarlos.',
    hook: '¿Buscas un maestro de obra o especialista disponible hoy?',
    ctaKeyword: 'RÁPIDO',
    targetTrade: 'maestro',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['disponible-hoy', 'urgencia', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 2 #24',
  },
  {
    id: 'CLI-RAP-INT-SIN-03',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Cansado de esperar comentarios? Recibe cotizaciones ya.\nComenta "YO" 👇',
    hook: '¿Cansado de esperar comentarios?',
    ctaKeyword: 'YO',
    suggestedEmoji: '👇',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['esperar-comentarios', 'cotizar-ya', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Rapidez Sin URL #1',
  },
  {
    id: 'CLI-RAP-INT-SIN-04',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Por qué esperar? Te paso varios plomeros listos para cotizar.\nEscríbeme 🔧',
    hook: '¿Por qué esperar?',
    suggestedEmoji: '🔧',
    targetTrade: 'plomero',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['plomeros-listos', 'dm', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Rapidez Sin URL #2',
  },
  {
    id: 'CLI-RAP-INT-SIN-05',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'No publiques en 5 grupos distintos.\nTe ayudo a encontrar uno ya. Comenta "YO" 👇',
    hook: 'No publiques en 5 grupos distintos.',
    ctaKeyword: 'YO',
    suggestedEmoji: '👇',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['evitar-multiples-grupos', 'rapidez', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Rapidez Sin URL #3',
  },
  {
    id: 'CLI-RAP-INT-SIN-06',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Deja de esperar respuestas.\nCompara varias cotizaciones a la vez. Comenta "YO" 👇',
    hook: 'Deja de esperar respuestas.',
    ctaKeyword: 'YO',
    suggestedEmoji: '👇',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['varias-cotizaciones', 'ahorro-tiempo', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Rapidez Sin URL #5',
  },
  {
    id: 'CLI-RAP-INT-SIN-07',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'No pierdas tiempo preguntando en varios grupos.\nComenta "YO" 👇 y te ayudo',
    hook: 'No pierdas tiempo preguntando en varios grupos.',
    ctaKeyword: 'YO',
    suggestedEmoji: '👇',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['sin-perder-tiempo', 'ayuda-inmediata', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Rapidez Sin URL #7',
  },
  {
    id: 'CLI-RAP-INT-SIN-08',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Necesitas cotizar un trabajo?\nEmpieza viendo quién puede hacerlo. 💬',
    hook: '¿Necesitas cotizar un trabajo?',
    suggestedEmoji: '💬',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['cotizar-trabajo', 'quien-lo-hace', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Rapidez #1',
  },
  {
    id: 'CLI-RAP-INT-SIN-09',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Buscas maestro?\nCompara trabajos antes de pedir cotización. 🛠️',
    hook: '¿Buscas maestro?',
    suggestedEmoji: '🛠️',
    targetTrade: 'maestro',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['comparar-antes-precio', 'maestro', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Rapidez #2',
  },
  {
    id: 'CLI-RAP-INT-SIN-010',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Encuentra profesionales y contacta directamente. 🔧',
    hook: 'Encuentra profesionales',
    suggestedEmoji: '🔧',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['contacto-directo', 'ultra-corto'],
    sourceOrigin: 'Manual 1 - Intriga + Rapidez #3',
  },
  {
    id: 'CLI-RAP-INT-SIN-11',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Necesitas arreglar algo?\nEncuentra quién puede ayudarte. 🏠',
    hook: '¿Necesitas arreglar algo?',
    suggestedEmoji: '🏠',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['arreglos', 'ayuda-rapida', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Rapidez #4',
  },
  {
    id: 'CLI-RAP-INT-SIN-12',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Busca el oficio que necesitas y conoce sus trabajos. 👷',
    hook: 'Busca el oficio que necesitas',
    suggestedEmoji: '👷',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['oficio', 'conocer-obras', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Rapidez #5',
  },
  {
    id: 'CLI-RAP-INT-SIN-13',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'RAPIDEZ',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: 'Antes de pedir precio, mira quién puede hacer el trabajo. 💬',
    hook: 'Antes de pedir precio',
    suggestedEmoji: '💬',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['precio-justo', 'idoneidad', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Rapidez #6',
  },
  {
    id: 'CLI-RAP-INT-SIN-14',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'INTRIGA',
    format: 'SIN_URL',
    copy: '¿Necesitas una cotización?\nPrimero encuentra buenas opciones. 🔨',
    hook: '¿Necesitas una cotización?',
    suggestedEmoji: '🔨',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['buenas-opciones', 'cotizar', 'corto'],
    sourceOrigin: 'Manual 1 - Intriga + Rapidez #7',
  },

  // ---------------------------------------------------------------------------
  // 8. RAPIDEZ -> INTRIGA -> CON_URL
  // ---------------------------------------------------------------------------
  {
    id: 'CLI-RAP-INT-CON-01',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'INTRIGA',
    format: 'CON_URL',
    copy: '¿Necesitas una cotización rápida?\nEncuentra especialistas de remodelación listos para atenderte en dezzpo.com.',
    hook: '¿Necesitas una cotización rápida?',
    targetTrade: 'remodelador',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['cotizacion-rapida', 'listos-atender', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 2 #21',
  },
  {
    id: 'CLI-RAP-INT-CON-02',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'INTRIGA',
    format: 'CON_URL',
    copy: 'Deja de publicar en mil grupos sin respuesta.\nEncuentra plomeros y electricistas cerca en dezzpo.com 🛠️',
    hook: 'Deja de publicar en mil grupos sin respuesta.',
    suggestedEmoji: '🛠️',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['sin-mil-grupos', 'cerca-de-ti', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 2 #22',
  },

  // ---------------------------------------------------------------------------
  // 9. RAPIDEZ -> BENEFICIO -> SIN_URL
  // ---------------------------------------------------------------------------
  {
    id: 'CLI-RAP-BEN-SIN-01',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Cotiza tu remodelación sin perder tiempo.\nComenta "PRECIO" y te enseño a conectar con maestros de tu zona.',
    hook: 'Cotiza tu remodelación sin perder tiempo.',
    ctaKeyword: 'PRECIO',
    targetTrade: 'remodelador',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['sin-perder-tiempo', 'zona-local', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 2 #29',
  },
  {
    id: 'CLI-RAP-BEN-SIN-02',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Conéctate directo con el plomero o electricista que necesitas para tu casa.\nEscribe "DIRECTO" y te paso el link.',
    hook: 'Conéctate directo con el plomero o electricista que necesitas',
    ctaKeyword: 'DIRECTO',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['conexion-directa', 'sin-esperas', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 2 #30',
  },
  {
    id: 'CLI-RAP-BEN-SIN-03',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Encuentra especialistas disponibles en tu barrio.\nResponde "ZONA" y te enviamos las opciones directas.',
    hook: 'Encuentra especialistas disponibles en tu barrio.',
    ctaKeyword: 'ZONA',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['geolocalizado', 'barrio', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 2 #31',
  },
  {
    id: 'CLI-RAP-BEN-SIN-04',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Recibe opciones de presupuesto para tu hogar sin cobros extra.\nComenta "PRESUPUESTO" y te ayudamos.',
    hook: 'Recibe opciones de presupuesto para tu hogar sin cobros extra.',
    ctaKeyword: 'PRESUPUESTO',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['sin-cobros-extra', 'presupuesto', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 2 #32',
  },
  {
    id: 'CLI-RAP-BEN-SIN-05',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: '¿Lo necesitas ya? Te paso opciones en minutos, no en días.\nMándame un mensaje 🛠️',
    hook: '¿Lo necesitas ya?',
    suggestedEmoji: '🛠️',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['en-minutos', 'urgencia-inmediata', 'dm'],
    sourceOrigin: 'Banco 3 - Rapidez Sin URL #4',
  },
  {
    id: 'CLI-RAP-BEN-SIN-06',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: '¿Urgente? Te conecto con varios profesionales ahora mismo.\nEscríbeme 🔧',
    hook: '¿Urgente?',
    suggestedEmoji: '🔧',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['urgente', 'varios-profesionales', 'dm'],
    sourceOrigin: 'Banco 3 - Rapidez Sin URL #6',
  },
  {
    id: 'CLI-RAP-BEN-SIN-07',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Recibe cotizaciones sin publicar en todos lados.\nMándame un mensaje 🛠️',
    hook: 'Recibe cotizaciones sin publicar en todos lados.',
    suggestedEmoji: '🛠️',
    targetTrade: 'general',
    painPoint: 'SPAM_MENSAJES',
    tags: ['privacidad', 'sin-spam-grupos', 'dm'],
    sourceOrigin: 'Banco 3 - Rapidez Sin URL #8',
  },
  {
    id: 'CLI-RAP-BEN-SIN-08',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: '¿Quieres varias opciones para elegir, no solo una?\nComenta "YO" 👇',
    hook: '¿Quieres varias opciones para elegir, no solo una?',
    ctaKeyword: 'YO',
    suggestedEmoji: '👇',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['comparar-opciones', 'anti-spam'],
    sourceOrigin: 'Banco 3 - Rapidez Sin URL #9',
  },
  {
    id: 'CLI-RAP-BEN-SIN-09',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Encuentra a alguien hoy mismo, no la próxima semana.\nEscríbeme 🔧',
    hook: 'Encuentra a alguien hoy mismo, no la próxima semana.',
    suggestedEmoji: '🔧',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['hoy-mismo', 'sin-dilacion', 'dm'],
    sourceOrigin: 'Banco 3 - Rapidez Sin URL #10',
  },
  {
    id: 'CLI-RAP-BEN-SIN-10',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Encuentra profesionales, mira sus trabajos y contacta para cotizar. 💬',
    hook: 'Encuentra profesionales, mira sus trabajos',
    suggestedEmoji: '💬',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['cotizar-directo', 'transparencia', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Rapidez #1',
  },
  {
    id: 'CLI-RAP-BEN-SIN-11',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Busca el oficio que necesitas y contacta directamente. 🛠️',
    hook: 'Busca el oficio que necesitas',
    suggestedEmoji: '🛠️',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['contacto-inmediato', 'ultra-corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Rapidez #2',
  },
  {
    id: 'CLI-RAP-BEN-SIN-12',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Encuentra opciones para tu proyecto y pide información. 🏠',
    hook: 'Encuentra opciones para tu proyecto',
    suggestedEmoji: '🏠',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['opciones-proyecto', 'pedir-info', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Rapidez #3',
  },
  {
    id: 'CLI-RAP-BEN-SIN-13',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'RAPIDEZ',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Mira trabajos reales antes de decidir a quién contactar. 🔧',
    hook: 'Mira trabajos reales',
    suggestedEmoji: '🔧',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['trabajos-reales', 'decision-informada', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Rapidez #4',
  },
  {
    id: 'CLI-RAP-BEN-SIN-14',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Encuentra profesionales para tu necesidad y habla directamente con ellos. 👷',
    hook: 'Encuentra profesionales para tu necesidad',
    suggestedEmoji: '👷',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['habla-directo', 'sin-intermediarios', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Rapidez #5',
  },
  {
    id: 'CLI-RAP-BEN-SIN-15',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Busca, compara y contacta profesionales para tu proyecto. 💬',
    hook: 'Busca, compara y contacta',
    suggestedEmoji: '💬',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['busca-compara-contacta', 'ultra-corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Rapidez #6',
  },
  {
    id: 'CLI-RAP-BEN-SIN-16',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'BENEFICIO',
    format: 'SIN_URL',
    copy: 'Encuentra quién puede hacer el trabajo que necesitas y pide cotización. 🔨',
    hook: 'Encuentra quién puede hacer el trabajo',
    suggestedEmoji: '🔨',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['pide-cotizacion', 'solucion-trabajo', 'corto'],
    sourceOrigin: 'Manual 1 - Beneficio + Rapidez #7',
  },

  // ---------------------------------------------------------------------------
  // 10. RAPIDEZ -> BENEFICIO -> CON_URL
  // ---------------------------------------------------------------------------
  {
    id: 'CLI-RAP-BEN-CON-01',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'BENEFICIO',
    format: 'CON_URL',
    copy: 'Cotiza tu arreglo o remodelación gratis.\nHabla directo con el especialista en dezzpo.com sin comisiones.',
    hook: 'Cotiza tu arreglo o remodelación gratis.',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['cero-comisiones', 'contacto-directo', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 2 #25',
  },
  {
    id: 'CLI-RAP-BEN-CON-02',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'BENEFICIO',
    format: 'CON_URL',
    copy: 'Ahorra tiempo buscando plomeros, electricistas o pintores cerca de tu casa en dezzpo.com.',
    hook: 'Ahorra tiempo buscando plomeros, electricistas o pintores',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['ahorro-tiempo', 'cerca-de-casa', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 2 #26',
  },
  {
    id: 'CLI-RAP-BEN-CON-03',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'BENEFICIO',
    format: 'CON_URL',
    copy: 'Resuelve tu problema de reparación o construcción sin pagar intermediarios en dezzpo.com.',
    hook: 'Resuelve tu problema de reparación o construcción',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['sin-intermediarios', 'solucion-rapida', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 2 #27',
  },
  {
    id: 'CLI-RAP-BEN-CON-04',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'BENEFICIO',
    format: 'CON_URL',
    copy: 'Encuentra gente experta para tu hogar fácil, rápido y con fotos de referencia en dezzpo.com.',
    hook: 'Encuentra gente experta para tu hogar',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['facil-rapido', 'fotos-referencia', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 2 #28',
  },

  // ---------------------------------------------------------------------------
  // 11. RAPIDEZ -> CONVERSIÓN -> SIN_URL
  // ---------------------------------------------------------------------------
  {
    id: 'CLI-RAP-CON-SIN-01',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'SIN_URL',
    copy: '¿Buscas un especialista en arreglos de hogar?\nEscribe "SOLICITUD" y te conectamos con perfiles disponibles.',
    hook: '¿Buscas un especialista en arreglos de hogar?',
    ctaKeyword: 'SOLICITUD',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['arreglos-hogar', 'perfiles-disponibles', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 2 #37',
  },
  {
    id: 'CLI-RAP-CON-SIN-02',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'SIN_URL',
    copy: 'Recibe cotizaciones para tu arreglo en menos de 24 horas.\nComenta "CASA" y te mandamos el directorio.',
    hook: 'Recibe cotizaciones para tu arreglo en menos de 24 horas.',
    ctaKeyword: 'CASA',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['24-horas', 'directorio-inmediato', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 2 #38',
  },
  {
    id: 'CLI-RAP-CON-SIN-03',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'SIN_URL',
    copy: 'Conecta hoy con el profesional adecuado para tu arreglo.\nDeja la palabra "QUIERO" aquí abajo.',
    hook: 'Conecta hoy con el profesional adecuado para tu arreglo.',
    ctaKeyword: 'QUIERO',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['profesional-adecuado', 'hoy', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 2 #39',
  },
  {
    id: 'CLI-RAP-CON-SIN-04',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'SIN_URL',
    copy: '¿Necesitas resolver una urgencia de plomería o electricidad?\nComenta "AHORA" para enviarte la lista de contactos.',
    hook: '¿Necesitas resolver una urgencia de plomería o electricidad?',
    ctaKeyword: 'AHORA',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['urgencia-inmediata', 'lista-contactos', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Eje 2 #40',
  },
  {
    id: 'CLI-RAP-CON-SIN-05',
    segment: 'INVENTO_NECESIDAD_DM',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'SIN_URL',
    copy: '¡Hola! Vi que buscas un profesional para tu casa. Te envié el catálogo por mensaje directo para que compares fotos antes de decidir.',
    hook: 'Vi que buscas un profesional para tu casa.',
    targetTrade: 'general',
    painPoint: 'SPAM_MENSAJES',
    tags: ['protocolo-2-pasos', 'respuesta-dm', 'anti-spam'],
    sourceOrigin: 'Manual 2 - Táctica Intercepción Paso 2',
  },

  // ---------------------------------------------------------------------------
  // 12. RAPIDEZ -> CONVERSIÓN -> CON_URL
  // ---------------------------------------------------------------------------
  {
    id: 'CLI-RAP-CON-CON-01',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Encuentra profesionales de construcción listos para cotizar tu proyecto en dezzpo.com.',
    hook: 'Encuentra profesionales de construcción listos para cotizar',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['cotizar-proyecto', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 2 #33',
  },
  {
    id: 'CLI-RAP-CON-CON-02',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Cotiza tu plomería, electricidad o pintura directamente en dezzpo.com y arregla tu casa ya.',
    hook: 'Cotiza tu plomería, electricidad o pintura directamente',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['arregla-tu-casa-ya', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 2 #34',
  },
  {
    id: 'CLI-RAP-CON-CON-03',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Encuentra especialistas de remodelación verificados hoy mismo en dezzpo.com.',
    hook: 'Encuentra especialistas de remodelación verificados',
    targetTrade: 'remodelador',
    painPoint: 'DESCONFIANZA',
    tags: ['verificados', 'hoy-mismo', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 2 #35',
  },
  {
    id: 'CLI-RAP-CON-CON-04',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Consigue el presupuesto que necesitas para tu casa ingresando gratis a dezzpo.com.',
    hook: 'Consigue el presupuesto que necesitas',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['presupuesto-gratis', 'directo'],
    sourceOrigin: 'Manual 2 - Eje 2 #36',
  },
  {
    id: 'CLI-RAP-CON-CON-05',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿Necesitas cotizar un trabajo?\nEncuentra profesionales en dezzpo.com 💬',
    hook: '¿Necesitas cotizar un trabajo?',
    suggestedEmoji: '💬',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['cotizar', 'profesionales', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Rapidez #1',
  },
  {
    id: 'CLI-RAP-CON-CON-06',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Busca quien haga el trabajo que necesitas y contacta en dezzpo.com 🛠️',
    hook: 'Busca quien haga el trabajo que necesitas',
    suggestedEmoji: '🛠️',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['contacto', 'solucion', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Rapidez #2',
  },
  {
    id: 'CLI-RAP-CON-CON-07',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Encuentra profesionales, mira sus trabajos y pide información en dezzpo.com 🔧',
    hook: 'Encuentra profesionales, mira sus trabajos',
    suggestedEmoji: '🔧',
    targetTrade: 'general',
    painPoint: 'DESCONFIANZA',
    tags: ['pedir-informacion', 'obras', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Rapidez #3',
  },
  {
    id: 'CLI-RAP-CON-CON-08',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿Necesitas plomero, electricista o pintor?\nBúscalo en dezzpo.com 🏠',
    hook: '¿Necesitas plomero, electricista o pintor?',
    suggestedEmoji: '🏠',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['oficios-multiples', 'busqueda-inmediata', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Rapidez #4',
  },
  {
    id: 'CLI-RAP-CON-CON-09',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Encuentra opciones para tu proyecto y contacta directo en dezzpo.com 👷',
    hook: 'Encuentra opciones para tu proyecto',
    suggestedEmoji: '👷',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['contacto-directo', 'proyecto', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Rapidez #5',
  },
  {
    id: 'CLI-RAP-CON-CON-10',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Busca profesionales para tu necesidad y solicita información en dezzpo.com 💬',
    hook: 'Busca profesionales para tu necesidad',
    suggestedEmoji: '💬',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['solicitar-info', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Rapidez #6',
  },
  {
    id: 'CLI-RAP-CON-CON-11',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Encuentra quién puede hacer tu proyecto en dezzpo.com 🔨',
    hook: 'Encuentra quién puede hacer tu proyecto',
    suggestedEmoji: '🔨',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['hacer-proyecto', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Rapidez #7',
  },
  {
    id: 'CLI-RAP-CON-CON-12',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Mira trabajos, compara opciones y contacta profesionales en dezzpo.com 🛠️',
    hook: 'Mira trabajos, compara opciones',
    suggestedEmoji: '🛠️',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['comparar-opciones', 'contacto', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Rapidez #8',
  },
  {
    id: 'CLI-RAP-CON-CON-13',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Encuentra el oficio que necesitas y pide cotización directamente. 🔧',
    hook: 'Encuentra el oficio que necesitas',
    suggestedEmoji: '🔧',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['cotizacion-directa', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Rapidez #9',
  },
  {
    id: 'CLI-RAP-CON-CON-14',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿Publicaste que necesitas un profesional?\nTambién puedes buscar opciones en dezzpo.com 🏠',
    hook: '¿Publicaste que necesitas un profesional?',
    suggestedEmoji: '🏠',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['interceptacion-post', 'buscar-opciones', 'directo'],
    sourceOrigin: 'Manual 1 - Conv + Rapidez #10',
  },
  {
    id: 'CLI-RAP-CON-CON-15',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿Cansado de esperar comentarios?\nEncuentra plomeros ya en dezzpo.com 🔧',
    hook: '¿Cansado de esperar comentarios?',
    suggestedEmoji: '🔧',
    targetTrade: 'plomero',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['plomeros-ya', 'sin-esperar', 'directo'],
    sourceOrigin: 'Banco 3 - Rapidez Con URL #11',
  },
  {
    id: 'CLI-RAP-CON-CON-16',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'No publiques en 5 grupos distintos.\nBusca y compara en dezzpo.com',
    hook: 'No publiques en 5 grupos distintos.',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['centralizacion', 'compara-en-un-lugar', 'directo'],
    sourceOrigin: 'Banco 3 - Rapidez Con URL #12',
  },
  {
    id: 'CLI-RAP-CON-CON-17',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿Lo necesitas ya?\nEncuéntralo en minutos en dezzpo.com 🛠️',
    hook: '¿Lo necesitas ya?',
    suggestedEmoji: '🛠️',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['en-minutos', 'urgencia', 'directo'],
    sourceOrigin: 'Banco 3 - Rapidez Con URL #13',
  },
  {
    id: 'CLI-RAP-CON-CON-18',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Deja de esperar respuestas.\nCompara varias cotizaciones en dezzpo.com',
    hook: 'Deja de esperar respuestas.',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['comparar-cotizaciones', 'directo'],
    sourceOrigin: 'Banco 3 - Rapidez Con URL #14',
  },
  {
    id: 'CLI-RAP-CON-CON-19',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿Urgente?\nEncuentra varios profesionales disponibles en dezzpo.com 🔧',
    hook: '¿Urgente?',
    suggestedEmoji: '🔧',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['urgente', 'disponibles', 'directo'],
    sourceOrigin: 'Banco 3 - Rapidez Con URL #15',
  },
  {
    id: 'CLI-RAP-CON-CON-20',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'No pierdas tiempo preguntando en 5 grupos.\nTodo está en dezzpo.com',
    hook: 'No pierdas tiempo preguntando en 5 grupos.',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['todo-en-dezzpo', 'ahorro-tiempo', 'directo'],
    sourceOrigin: 'Banco 3 - Rapidez Con URL #16',
  },
  {
    id: 'CLI-RAP-CON-CON-21',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Recibe cotizaciones sin publicar en todos lados:\ndezzpo.com',
    hook: 'Recibe cotizaciones sin publicar en todos lados',
    targetTrade: 'general',
    painPoint: 'SPAM_MENSAJES',
    tags: ['sin-spam', 'directo'],
    sourceOrigin: 'Banco 3 - Rapidez Con URL #17',
  },
  {
    id: 'CLI-RAP-CON-CON-22',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: '¿Quieres varias opciones para elegir?\nCompáralas en dezzpo.com',
    hook: '¿Quieres varias opciones para elegir?',
    targetTrade: 'general',
    painPoint: 'INFORMALIDAD_PRECIOS',
    tags: ['varias-opciones', 'directo'],
    sourceOrigin: 'Banco 3 - Rapidez Con URL #18',
  },
  {
    id: 'CLI-RAP-CON-CON-23',
    segment: 'RESPUESTA_DIRECTA',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Encuentra a alguien hoy mismo en dezzpo.com, no la próxima semana',
    hook: 'Encuentra a alguien hoy mismo en dezzpo.com',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['hoy-mismo', 'directo'],
    sourceOrigin: 'Banco 3 - Rapidez Con URL #19',
  },
  {
    id: 'CLI-RAP-CON-CON-24',
    segment: 'POST_PUBLICO_SOLUCION',
    angle: 'RAPIDEZ',
    intent: 'CONVERSION',
    format: 'CON_URL',
    copy: 'Ahorra tiempo buscando.\nTodo en un solo lugar: dezzpo.com 🔧',
    hook: 'Ahorra tiempo buscando.',
    suggestedEmoji: '🔧',
    targetTrade: 'general',
    painPoint: 'LENTITUD_URGENCIA',
    tags: ['un-solo-lugar', 'directo'],
    sourceOrigin: 'Banco 3 - Rapidez Con URL #20',
  },
] as const;

// =============================================================================
// STARTER PACK: TOP 6 PARA INTERCEPTACIÓN RÁPIDA (TESTING A/B)
// =============================================================================

export const CLIENT_INTERCEPT_STARTER_PACK: readonly string[] = [
  'CLI-CONF-INT-SIN-11', // ¿Buscas un profesional? Mira primero lo que sabe hacer. 🔧
  'CLI-CONF-INT-SIN-12', // Antes de contratar, conoce los trabajos que ha realizado. 🛠️
  'CLI-RAP-BEN-SIN-10',  // Encuentra profesionales, mira sus trabajos y contacta para cotizar. 💬
  'CLI-RAP-BEN-SIN-16',  // Encuentra quién puede hacer el trabajo que necesitas y pide cotización. 🔨
  'CLI-CONF-CON-CON-05', // ¿Buscas plomero, electricista o maestro? Encuéntralo en dezzpo.com 🔧
  'CLI-RAP-CON-CON-12',  // Mira trabajos, compara opciones y contacta profesionales en dezzpo.com 🛠️
] as const;

// =============================================================================
// ADAPTACIÓN AL CONTEXTO DE CADA PUBLICACIÓN
// =============================================================================

export interface ContextTriggerResponse {
  readonly queryPattern: string;
  readonly recommendedCopy: string;
  readonly targetTrade: TargetTrade;
  readonly rationale: string;
}

export const CONTEXT_TRIGGER_RESPONSES: readonly ContextTriggerResponse[] = [
  {
    queryPattern: 'Solicito plomero / Busco plomería',
    recommendedCopy: '🚰 ¿Buscas plomero? Mira sus trabajos y encuentra opciones en dezzpo.com',
    targetTrade: 'plomero',
    rationale: 'Responde específicamente con el oficio solicitado en vez de términos genéricos.',
  },
  {
    queryPattern: 'Necesito electricista urgente / Corto circuito',
    recommendedCopy: '⚡ Busca electricistas, mira sus trabajos y contacta directamente en dezzpo.com',
    targetTrade: 'electricista',
    rationale: 'Ataca el dolor de urgencia con llamada a la acción de contacto directo.',
  },
  {
    queryPattern: 'Busco maestro para remodelación / Obra blanca',
    recommendedCopy: '🛠️ Encuentra maestros y conoce sus trabajos antes de contactarlos en dezzpo.com',
    targetTrade: 'maestro',
    rationale: 'Mitiga el miedo a malas remodelaciones enfatizando ver trabajos previos.',
  },
  {
    queryPattern: 'Solicito cotización para pintura / Pintor',
    recommendedCopy: '🎨 Mira trabajos de pintores y encuentra opciones para cotizar en dezzpo.com',
    targetTrade: 'pintor',
    rationale: 'Ofrece comparación visual de acabados antes de pedir presupuesto.',
  },
] as const;

// =============================================================================
// HELPER UTILITIES
// =============================================================================

/**
 * Filter client interception copy catalog by segment, angle, intent, format, trade, or pain point.
 */
export function getFilteredInterceptCopys(options: InterceptFilterOptions): readonly ClientCopyItem[] {
  return CLIENT_INTERCEPT_COPYS.filter((item) => {
    if (options.segment && item.segment !== options.segment) return false;
    if (options.angle && item.angle !== options.angle) return false;
    if (options.intent && item.intent !== options.intent) return false;
    if (options.format && item.format !== options.format) return false;
    if (options.targetTrade && item.targetTrade !== options.targetTrade && item.targetTrade !== 'general') {
      return false;
    }
    if (options.painPoint && item.painPoint !== options.painPoint) return false;
    if (options.tag && !item.tags.includes(options.tag)) return false;
    return true;
  });
}

/**
 * Retrieve a single client copy by ID.
 */
export function getInterceptCopyById(id: string): ClientCopyItem | undefined {
  return CLIENT_INTERCEPT_COPYS.find((c) => c.id === id);
}

/**
 * Retrieve a random client interception copy matching specific criteria.
 */
export function getRandomInterceptCopy(options: InterceptFilterOptions): ClientCopyItem | undefined {
  const filtered = getFilteredInterceptCopys(options);
  if (filtered.length === 0) return undefined;
  const randomIndex = Math.floor(Math.random() * filtered.length);
  return filtered[randomIndex];
}

/**
 * Builds a UTM tracking URL for client demand interception traffic.
 */
export function buildClientUtmUrl(
  baseUrl = 'https://dezzpo.com',
  copyId: string,
  utmParams?: ClientUtmParameters
): string {
  const url = new URL(baseUrl);
  url.searchParams.set('utm_source', utmParams?.source ?? 'facebook');
  url.searchParams.set('utm_medium', utmParams?.medium ?? 'group_interception');
  url.searchParams.set('utm_campaign', utmParams?.campaign ?? 'demand_homeowners');
  url.searchParams.set('utm_content', utmParams?.content ?? copyId);
  if (utmParams?.term) {
    url.searchParams.set('utm_term', utmParams.term);
  }
  return url.toString();
}

/**
 * Dynamic string interpolation for hyper-segmented client demand responses.
 */
export function interpolateClientCopy(
  template: string,
  variables: {
    trade?: string;
    cityOrZone?: string;
    keyword?: string;
  }
): string {
  let result = template;
  if (variables.trade) {
    result = result.replace(/\{oficio\}/gi, variables.trade);
  }
  if (variables.cityOrZone) {
    result = result.replace(/\{zona\}/gi, variables.cityOrZone);
  }
  if (variables.keyword) {
    result = result.replace(/\{keyword\}/gi, variables.keyword);
  }
  return result;
}
